### ISSUE TITLE
Refactor addresses to use only token addresses

### ISSUE THREAD

**Issue by chikeichan** [Uniswap/uniswap-frontend#106]
Currently, we hardcoded `exchangeAddresses` and `tokenAddresses` to initialize first list of tokens. We should refactor so that we only need to maintain a list of `tokenAddresses`.

DoD:
- refactor addresses duck so that it only keep track of a list of tokenAddresses
- on app load, start fetching all necessary info: getExchange, token label, token decimals
- persist in local storage so we don't have to fetch again on next load

**Comment by destenson** [comment]
The factory contract is capable of providing all the exchanges it's created. There's no need to hard-code token addresses at all.

It'd be ideal if the front-end iterated through them and only displayed tokens with non-zero liquidity, i.e. trade-able tokens.

**Comment by haydenadams** [comment]
The issue with showing all possible tokens in the factory is that there are no checks on what tokens can be added to the factory. Some tokens can be malicious and should not be displayed. IMO the best option is to have a list of the top 200 ERC20 tokens by market cap, and then anything outside that list users have to manually add (saved to local storage).

**Comment by destenson** [comment]
While that is true, it's unlikely that someone would commit liquidity to a bad token. A check on the balance of the exchange would pretty easy.

**Comment by destenson** [comment]
On local storage, I think any exchange & addresses should be cached there anyway, since they _never_ change.

**Comment by haydenadams** [comment]
> While that is true, it's unlikely that someone would commit liquidity to a bad token. A check on the balance of the exchange would pretty easy.
 
Imagine someone deploying an identical version of DAI, with the only difference being that they have 100% of supply. They can then create an exchange for it and add as much liquidity to it as they want. There is no risk whatsoever of them losing ETH through ERC20>ETH swaps because no one else owns fake DAI. However others can be tricked into buying fake DAI with real ETH. There is no easy solution to this problem I know of.

> You've got a great idea going here, let's not centralize it too much or make it dependent on external data feeds.

It's super easy to fork and host your own Uniswap frontend. The code in this repo is just a suggestion for how it can be done safely. Will write a guide soon, if you want to make one susceptible to attacks like this!

**Comment by destenson** [comment]
You make a good point about counterfeit tokens. I have an idea for a solution about that, but I'll mull it over more before making too big a fool of myself.

WRT to the proposed improvements, I've already forked the frontend & have begun to start customizing it. I didn't mean to imply that you had to do it. If I come up with anything good, I'll share it with you.

**Comment by haydenadams** [comment]
@destenson cool! Very interested in solutions here. You should join the slack if you're actively playing around with code! 

https://join.slack.com/t/uni-swap/shared_invite/enQtNDYwMjg1ODc5ODA4LWEyYmU0OGU1ZGQ3NjE4YzhmNzcxMDAyM2ExNzNkZjZjZjcxYTkwNzU0MGE3M2JkNzMxOTA2MzE2ZWM0YWQwNjU

**Comment by NoahZinsmeister** [comment]
the data structure aspect of this issue has been addressed in the beta branch, where tokens are now organized exclusively by token address. for now, all relevant token details (name, symbol, decimals, and exchange address) are also hard-coded to reduce network overhead. in the future we would like to improve this setup, let's continue the discussion in another thread!
