### ISSUE TITLE
Loading state when loading arbitrary token

### ISSUE THREAD

**Issue by chikeichan** [Uniswap/uniswap-frontend#111]
Currently, after entering arbitrary token into the token select modal, the text "No Exchange Found" shows up immediately, and then go away if an exchange is found.

DoD:
- We need to show a loading state when we are waiting for response on `getExchange`
- Just a spinner + `Searching for exchange...` instead of the `No Exchange Found` text should be good for now - @callil let me know if this is good.

**Comment by haydenadams** [comment]
Fixed in https://github.com/Uniswap/uniswap-frontend/pull/141
