### ISSUE TITLE
Slow Network Handling

### ISSUE THREAD

**Issue by chikeichan** [Uniswap/uniswap-frontend#113]
Let's discuss all things slow network here

Slow network response sometimes causes unexpected behavior. Some known issues are:
- Exchange Rate would initially show as `0` or `Infinity`
- throw `decimals` error when adding arbitrary token
- Flashes of `No Exchange Found` when adding arbitrary token

I think we should also add some slow network message. I think CryptoKitties has something like "Network is slow - some feature might have degraded experience" with some meow puns somewhere in there.

**Comment by callil** [comment]
I'd like to explore having a connection status indicator permanently shown in the top bar.

**Comment by NoahZinsmeister** [comment]
the bugs around this are largely fixed in the beta branch, we can discuss a connection status indicator in another thread!
