### ISSUE TITLE
Update exchange values with tick effect

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-frontend#116]
Implement something like: https://github.hubspot.com/odometer/docs/welcome/ to help communicate the web3 connection status and give users confidence in the system. We should use this method to be checking connection status (#113) and communicate if web3 is taking longer than expected to respond.

**Comment by NoahZinsmeister** [comment]
closing this issue to clean up the github, but i want to integrate it soon! let's migrate it to whatever feature tracking system we end up adopting @callil! could even be github, in which case we can just open another issue.
