### ISSUE TITLE
Frontend Miscalculates Exchange Rate for GUSD When Adding Liquidity

### ISSUE THREAD

**Issue by veekta** [Uniswap/uniswap-frontend#126]
The web UI miscalculates the exchange rate for GUSD (token address: 0x056fd409e1d7a124bd7017459dfea2f387b6d5cd) , making it difficult to add additional liquidity to the exchange.

![image](https://user-images.githubusercontent.com/7054770/48282481-cc76df00-e427-11e8-836c-456bb2d3fe5d.png)

**Comment by haydenadams** [comment]
@veekta this was fixed in https://github.com/Uniswap/uniswap-frontend/pull/129
