### ISSUE TITLE
Values that are less than decimal precisions but greater than 0

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#137]
Example:

![image](https://user-images.githubusercontent.com/9343483/48491092-cb153000-e7f4-11e8-8b4c-ca8f8688845f.png)

Here it should say:

"Your pool share (< 0.00%)" and "< 0.00 + 2 FUN"

**Comment by WyseNynja** [comment]
What caused such a small amount to be left behind? Is dust like this expected to be common?

**Comment by haydenadams** [comment]
.01 ETH is $1.50 as of right now. It's very possible for values below that. Not sure how common it will be but we should have a standard way for dealing with low, nonzero values.

Pool shares below 0.01% are expected, especially once there are multi-million dollar pools.

**Comment by NoahZinsmeister** [comment]
this is fixed in the beta branch
