### ISSUE TITLE
Increase tx speed (and gas fee)

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#140]
I believe the current formula is average of last 10 blocks or something. I think increasing it 25% would be a good move.

**Comment by WyseNynja** [comment]
There should probably be an explanation given when the user hovers the fee explaining why low fees are a problem.

**Comment by kaibakker** [comment]
Who has an incentive to front-run me? What else would be a good reason want a higher transaction speed?

**Comment by haydenadams** [comment]
@kaibakker I'm mostly thinking faster = better from a UX perspective. Uniswap gas fees are frequently as lower as $0.03. Also Uniswap sets the tx timeout to 5mins - if transactions take longer, they will fail.

**Comment by kaibakker** [comment]
Why would you set such a strict time window, if you could restrict the price to be maximal 0.5% lower than the current market price?

**Comment by haydenadams** [comment]
Limit miners holding signed transactions and only executing them based on future market movements. Also if you don't have time limits, pending txs put your tokens in limbo. You don't know if they will be spent or not. Putting a deadline mitigates this.

Agreed it could be longer.
