### ISSUE TITLE
Clicking on account should show address and pending transactions

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#143]
Even if there are no pending transactions the modal should pop up with just the address. This should have a copy to clipboard button and an open in etherscan button. 

Pending transactions should also get a copy transaction hash button in addition to the open in etherscan button. 

UX below is just an example of what it could look like.

<img width="277" alt="screen shot 2018-11-14 at 1 34 38 pm" src="https://user-images.githubusercontent.com/9343483/48504189-26a1e680-e812-11e8-958b-a8f62e3a39af.png">

**Comment by NoahZinsmeister** [comment]
this is fixed!
