### ISSUE TITLE
Clicking center arrow in swap and send should flip input and output tokens

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#147]

**Comment by mikedemarais** [comment]
i can take this if @kennyt hasnt started!

**Comment by kennyt** [comment]
@mikedemarais I started on this issue already. a PR for this issue is here: https://github.com/Uniswap/uniswap-frontend/pull/151

**Comment by WyseNynja** [comment]
I think this can be closed. Clicking the arrow worked for me. Thanks!
