### ISSUE TITLE
getExchange loading state never ends if token does not have an exchange

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#149]
Error since: https://github.com/Uniswap/uniswap-frontend/pull/141/commits/84bf3c7d002c5471e9745668f92457ae0c19245a

When getExchange returns 0x000000.... users should be prompted to "Create exchange' but instead it just stays on the "Searching for exchange" loading state indefinitely.

**Comment by kennyt** [comment]
added a fix for this in #131

**Comment by NoahZinsmeister** [comment]
this should be fixed!
