### ISSUE TITLE
Warning for large trades

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#153]
Trades with greater than ~10% slippage should get a warning. Example:

https://etherscan.io/tx/0x1a2d3b0a4321f1a75e3a396d91fb2e07e8debd62bbe099724303960e7fe9e8ef

Might need some ux here @callil

**Comment by callil** [comment]
Some screens for this: 

The idea is to keep the warnings and error states in the same section. I've added a yellow as a warning color in this case (red should be kept for trade blocking issues only)

Warning Prompt:

<img width="637" alt="screen shot 2019-02-05 at 9 24 53 am" src="https://user-images.githubusercontent.com/1355319/52280035-e477d500-2928-11e9-99e6-57d9c5b1f445.png">

Warning Expanded:
<img width="480" alt="screen shot 2019-02-05 at 9 25 05 am" src="https://user-images.githubusercontent.com/1355319/52280051-efcb0080-2928-11e9-9fe0-55f9d1679b0e.png">

I'm not a big fan of showing slippage be default in the interest of keeping things as simple as possible. Showing slippage in the dropdown follows our concept of advanced information one click away, and users can keep the dropdown open to see how adjusting the numbers changes the slippage amount.

**Comment by haydenadams** [comment]
@callil Adjusted the copy. How about this?

<img width="546" alt="screen shot 2019-02-05 at 2 44 17 pm" src="https://user-images.githubusercontent.com/9343483/52299922-ab555a00-2954-11e9-97b8-4b9a6941101c.png">

and

<img width="562" alt="screen shot 2019-02-05 at 2 44 30 pm" src="https://user-images.githubusercontent.com/9343483/52299936-b1e3d180-2954-11e9-9601-0704def14d0a.png">

**Comment by amcassetti** [comment]
Looks great. What do you think qualifies as high slippage, 2%?

**Comment by haydenadams** [comment]
@amcassetti I was thinking 2% or 3%

**Comment by amcassetti** [comment]
@haydenadams either seems reasonable

**Comment by banteg** [comment]
<img width="568" alt="image" src="https://user-images.githubusercontent.com/4562643/52794944-655e6b80-30a3-11e9-9a46-c7838c2a264b.png">

how about something like this? it helps in getting the idea of how deep the pool is and can be emphasized if the trade results in high slippage.

**Comment by amcassetti** [comment]
@banteg that looks nice.

a thought around the label:

"price slippage" will make sense to users like us, but if the goal is to also target non-technical users, something along the lines of "exchange fee" could be better. my hunch is most people already understand what fees are.

not sure if it would be technically misleading, but at the end of the day, slippage and fees sort of results in the same thing - less tokens for you.

**Comment by NoahZinsmeister** [comment]
slippage warning designs are finalized, and will be released on the beta branch soon™
