### ISSUE TITLE
Clicking an inputs/outputs "Balance:" label should populate input with "Max value"

### ISSUE THREAD

**Issue by mikedemarais** [Uniswap/uniswap-frontend#154]
Clicking this `Balance: 2.5021` label should act as a **Max** button, populating the input with the complete available balance.

We could add a "save some for gas" warning when the selected asset is ETH

![](https://cl.ly/c8935a5a5e68/download/uniswap_max_input.png)

**Comment by haydenadams** [comment]
Agreed! It's something we've talked about in the past but never got around to.
