### ISSUE TITLE
Testnet Deployment

### ISSUE THREAD

**Issue by fubuloubu** [Uniswap/uniswap-frontend#158]
Would be cool to try it out or demonstrate it to a larger group using a testnet that has some tokens on it.

**Comment by woeltjen** [comment]
Looks like there's a [Rinkeby deployment](https://github.com/Uniswap/uniswap-frontend/blob/master/src/ducks/addresses.js#L1)

A Ropsten deployment would be useful for me (and I imagine a Kovan deployment would be useful for others). If I end up deploying one, I'll submit a PR here; it seems like a resource that will be more useful when shared.

**Comment by haydenadams** [comment]
Here's rinkeby:
https://hackmd.io/SHPZJPSUTSW8se71CP_TBA

Here's kovan:
https://hackmd.io/OlNJB9a-QJCn8t9BfpOOfg

Here's deploy instructions:
https://github.com/Uniswap/contracts-vyper/issues/12#issuecomment-452168598

**Comment by fubuloubu** [comment]
@woeltjen did you end up making a ropsten deployment?

**Comment by woeltjen** [comment]
@fubuloubu Yep, [0x9c83dCE8CA20E9aAF9D3efc003b2ea62aBC08351](https://ropsten.etherscan.io/address/0x9c83dce8ca20e9aaf9d3efc003b2ea62abc08351).

**Comment by fubuloubu** [comment]
Awesome! Hosting the dapp?

**Comment by woeltjen** [comment]
I've been interacting with Uniswap from other contract code, primarily (and a bit via MEW). Got a start on a PR to reference those addresses here, hopefully will find time to finish that up in the nearish future.

**Comment by fubuloubu** [comment]
@haydenadams would it make sense to have `(ropsten|rinkeby).uniswap.exchange` sites?

**Comment by adamskrodzki** [comment]
Any plan to connect rinkeby with UI (so instead of 'wrong network' it will allow for test trades) ?

**Comment by justinjmoses** [comment]
Having a uniswap frontend for use with testnets would be a real nice-to-have for projects to take advantage of uniswap instead of writing custom faucets. We're a bit too stretched to do the UI for `SNX` so I'll use the contracts for now, but `(ropsten|rinkeby|kovan).uniswap.exchange` would be a huge boon for projects looking to bootstrap testnet liquidity.

**Comment by fubuloubu** [comment]
`goerli` would be the best, as we it is cross-client, will be running the ETH 2.0 bridge, and we should be encouraging it's use
