### ISSUE TITLE
Feature request: Interface element to "swap" input and output token in swap and send interface

### ISSUE THREAD

**Issue by pascalvanhecke** [Uniswap/uniswap-frontend#161]
![uniswap exchange 2018-12-09 00-07-16](https://user-images.githubusercontent.com/290665/49691598-99b72800-fb46-11e8-9366-1b55dc98c374.png)

Clicking the red arrow would make BAT and ETH switch between themselves.

**Comment by callil** [comment]
waiting on the merge:  #151

**Comment by haydenadams** [comment]
closing since https://github.com/Uniswap/uniswap-frontend/issues/147 is still open
