### ISSUE TITLE
Adding New Exchange

### ISSUE THREAD

**Issue by osyed** [Uniswap/uniswap-frontend#163]
I used the Uniswap UI to create a new exchange for Unblocked Ledger Token (ULT) using this page:
https://uniswap.exchange/create-exchange

The transaction was successful as shown here:
https://etherscan.io/tx/0x4c5639e6c59f04c76bde6784b9f8cb63b632f095945f0659f3a0b72de787ebe7

Now I would like to add liquidity, but don't see ULT listed as one of the tokens that can be selected on this page:
https://uniswap.exchange/add-liquidity

Is this list of tokens automatically generated or does a request have to be made to add a token to this list?

**Comment by osyed** [comment]
Someone mentioned on Reddit that the contract address could be entered into the search bar. I didn't know the contract address could be entered into the search bar. I see now that it does say "Search Token or Paste Address". I read that, but didn't know what Address to paste. It would help to say "Contract Address"

So it seems that someone is curating the list of tokens. I would like to know what the criteria is to be included in the list of tokens on uniswap.exchange? Is there some liquidity threshold to be included in the list? I could not find any info about this.

**Comment by haydenadams** [comment]
Closing this thread. Check out: https://github.com/Uniswap/uniswap-frontend/issues/163 for continued discussion
