### ISSUE TITLE
Frontend gives the end-user an opportunity to perform the "unlock" function even if their account  does not hold any of those tokens

### ISSUE THREAD

**Issue by tpmccallum** [Uniswap/uniswap-frontend#171]
The frontend will give the end-user an opportunity to perform the "unlock" function even if their account  does not hold any of those tokens i.e. the unlock succeeds and then the next progression is that the end-user gets an insufficient balance message.
Perhaps a pre-check (in relation to the selected token) before rendering the Unlock button is required.
This will save on wasted gas and unnecessary on-chain transactions in the event that end-users unnecessarily perform the unlock function for tokens that don't concern them.

**Comment by NoahZinsmeister** [comment]
this is fixed in the beta branch
