### ISSUE TITLE
Repeated check for existing tokens

### ISSUE THREAD

**Issue by GNSPS** [Uniswap/uniswap-frontend#172]
This seems like a repetition:

https://github.com/Uniswap/uniswap-frontend/blob/966a2800093938a7dce26a6d58c00ec0465e80d0/src/ducks/addresses.js#L121-L124

**Comment by tpmccallum** [comment]
Indeed it is @GNSPS - nicely spotted 👍 
A pull request which removed this line was merged into the dev branch only about 10 days ago.
Reference: https://github.com/Uniswap/uniswap-frontend/pull/146
Thanks

**Comment by GNSPS** [comment]
Perfect! 😄
