### ISSUE TITLE
UI should adjust with window size

### ISSUE THREAD

**Issue by rossbulat** [Uniswap/uniswap-frontend#180]
The majority of interest will stem from mobile and use with mobile clients like Cipher. Uniswap needs to have a responsive design.

Solution: maintain current design, introduce media queries to adjust layout.

Rationale: Uniswap is a lightweight client, as such bootstrapping UI libraries would be overkill. Simple CSS refactoring with media queries will suffice.

Below is a screenshot of Uniswap in Safari's responsive design mode, displaying how Uniswap looks on the iPhone 8.

<img width="708" alt="screenshot 2019-01-03 at 12 20 40" src="https://user-images.githubusercontent.com/13929023/50624350-00ffa680-0f52-11e9-8892-d8ab966c2a04.png">

**Comment by haydenadams** [comment]
This is what I get on mobile safari:
![img_8f934701b20d-1](https://user-images.githubusercontent.com/9343483/50626113-58722800-0efa-11e9-8e7e-741199dfa0cf.jpeg)

This is what I get on desktop safari:
<img width="868" alt="screen shot 2019-01-03 at 1 55 02 am" src="https://user-images.githubusercontent.com/9343483/50626159-a6872b80-0efa-11e9-860e-7a2e867db22c.png">

This is what I get on an iPhone8:
<img width="914" alt="screen shot 2019-01-03 at 1 43 00 am" src="https://user-images.githubusercontent.com/9343483/50626174-ba329200-0efa-11e9-8921-8fdbeef6ce63.png">

This is what it get in cipher:
![img_2de4118fd7b7-1](https://user-images.githubusercontent.com/9343483/50626207-ed752100-0efa-11e9-96ae-145f1486879e.jpeg)

**Comment by haydenadams** [comment]
Fixed in https://github.com/Uniswap/uniswap-frontend/pull/182
