### ISSUE TITLE
Validation box is out of context. No help dialogues

### ISSUE THREAD

**Issue by rossbulat** [Uniswap/uniswap-frontend#181]
The validation box is out of context, and there are no help dialogues.

This is demonstrated below. The box is always fixed at the bottom of the window:

<img width="861" alt="uniswap-dialogue" src="https://user-images.githubusercontent.com/13929023/50624477-5b4d3700-0f53-11e9-98cd-690799ce51b3.png">

Solution:

(a) Display error messages underneath a textbox, or beside the textbox label.

(b) Introducing guided notes with Joyride (NPM [here](https://www.npmjs.com/package/react-joyride), Demo [here](https://react-joyride.com))

(a) and (b) used in conjunction would make the footer obsolete. Could then focus on a more full screen, flexbox supported layout.

**Comment by haydenadams** [comment]
@rossbulat what do you think about this update? You might need to clear cache to see it.

https://github.com/Uniswap/uniswap-frontend/pull/185

**Comment by rossbulat** [comment]
@haydenadams  Thanks, I'll take a look
