### ISSUE TITLE
Add new Uniswap icon

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#187]
As shown:

<img width="943" alt="50738644-bb9fdb00-11d6-11e9-83b8-9997a380929a" src="https://user-images.githubusercontent.com/9343483/50778974-2c91d200-126d-11e9-8182-1b6d6447a01e.png">

**Comment by mikedemarais** [comment]
i hate this

**Comment by mikedemarais** [comment]
@haydenadams 
how about using an open source 🦄️ unicorn emoji? 

theres OpenMoji:
http://openmoji.org/library.html?search=unicorn&emoji=1F984

and twitter's "twemoji":
https://github.com/twitter/twemoji
![](https://cl.ly/e5a6c0abf95a/download/1f984.png)

**Comment by callil** [comment]
I think it's worth an open call for a illustrator to make a better unicorn for us! 

I like openMoji's better - I wonder if we can fork and use the uniswap colors in its design.

**Comment by rossbulat** [comment]
Something abstract.
Something more badass.
Something modern and vector friendly.
 
![uni](http://jkrb.stream/misc/uniConcept.png)

Adapted from https://www.flaticon.com/free-icon/unicorn-head-horse-with-a-horn_33118

**Comment by nodeap** [comment]
![uniswap3](https://user-images.githubusercontent.com/46633135/51077624-440af980-1677-11e9-896c-dc217469bdeb.jpg)

Here's a rough idea, can tweak if you guys like the overall concept with this one

Thanks

**Comment by rossbulat** [comment]
https://pngtree.com/freepng/unicorn-abstract-icon_3633531.html

**Comment by mattnumber** [comment]
My wife drew this on paper as a prototype - the idea is two cute unicorns that form a sortof yin-yang circle, where one is pink + one is white w/ a pink horn (they could maybe be smushed together more). The idea behind them being chubby + cute is that anybody can be a unicorn, just like anybody can add liquidity to Uniswap

https://github.com/mattnumber/bullicornz/blob/master/bullicorns.jpg

**Comment by scott-l-e-w-i-s** [comment]
main logo is a abstract-y unicorn (ripped from noun project with proper payments, creative commons) altered to feature lisa frank-y colors and a reflection of itself in an unseen _pool_ below.

more compact logo is just the abstract-y unicorn with lisa frank colors without reflection. have svgs.

![unicorn-no-reflection](https://user-images.githubusercontent.com/41017166/51360596-e4a35400-1a91-11e9-8257-33508356bb31.png)
![unicorn-with-reflection](https://user-images.githubusercontent.com/41017166/51360597-e4a35400-1a91-11e9-8627-86e445afba12.png)

**Comment by sassal** [comment]
I like @rossbulat's :)

**Comment by laurenbostick** [comment]
simple shapes silhouette, easily scalable

![image](https://user-images.githubusercontent.com/46848371/51430229-19c0bb00-1be6-11e9-845f-414e3c58ada4.png)

**Comment by haydenadams** [comment]
@laurenbostick Across all Uniswap websites / social media profiles and as the icon in dapp browsers.

**Comment by ChristophSiegenthaler** [comment]
![unicorn svg](https://user-images.githubusercontent.com/22180726/53050152-f618bb00-3498-11e9-8724-3271d24bce53.png)

I made something :)

**Comment by kaibakker** [comment]
Uniswap should make the :unicorn: emoji it's official logo. Uniswap and Unicode emojis are both open and in the public domain. The unicorn emoji is part of Uniswaps early succes. It is also easy to share it on any platform: when you are building a website, sending a tweet or even typing a message on slack, it's easy to include to the uniswap logo!

**Comment by mikedemarais** [comment]
fwiw i 💯 agree with @kaibakker about using 🦄 emoji as logo, but y’all already know my stance

**Comment by haydenadams** [comment]
We have a new icon coming soon ;)
