### ISSUE TITLE
Add link to documentation

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#188]
<img width="943" alt="50738644-bb9fdb00-11d6-11e9-83b8-9997a380929a" src="https://user-images.githubusercontent.com/9343483/50779050-5f3bca80-126d-11e9-9ee2-0d0a22cd9015.png">

**Comment by NoahZinsmeister** [comment]
For reference, the link should be `https://docs.uniswap.io/`. I propose https://feathericons.com/?query=book-open as the logo
