### ISSUE TITLE
Is there any reason to pool WETH?

### ISSUE THREAD

**Issue by WyseNynja** [Uniswap/uniswap-frontend#189]
I noticed that there is a pool for ETH/WETH. Why would someone want to add liquidity to this pool? It seems like the gas cost to wrap/unwrap the ETH directly would be cheaper.

The current exchange rate is 1 ETH = 1.0008 WETH and there are 60.46 ETH in the pool so someone must think it is worthwhile.

**Comment by woeltjen** [comment]
Yes.

My use case is payments via utility token. Want to *receive* payment in the specific token, but want to *accept* payment in whatever the end user has. Working on a solution which uses Uniswap to make the distinction transparent at the time of payment. For such a system, the WETH pool means accepting WETH without ever having to think about WETH. (Same goes for any other token with a more value-efficient but token-specific exchange mechanism.)

So, there's a concrete case for the convenience @haydenadams mentioned.

**Comment by haydenadams** [comment]
@woeltjen one thing to note is that unless the ETH-WETH pool gets much larger, its much better to wrap/unwrap eth using the wrapper contract and then swap the unwrapped eth on uniswap

**Comment by kaibakker** [comment]
I believe removing the WETH market from the main list would be helpful, it just not really a product uniswap should be advertising.

**Comment by ChristophSiegenthaler** [comment]
IMO any reasonably large liquidity pool should be in the default list, WETH included. We'll see if it gets used but I wouldn't leave it out just to "train" people to use ETH instead.

**Comment by haydenadams** [comment]
Hmm I kinda agree w/ @kaibakker . I think its a fun market to have/watch but if theres a wrapper on the frontend it should prob use the WETH contract

**Comment by haydenadams** [comment]
Everything will use WETH in V2 in the background, we will still have helper functions for natively supporting ETH
