### ISSUE TITLE
Add liquidity: Unlock displayed (with unlocked tokens) when ETH field is cleared

### ISSUE THREAD

**Issue by rossbulat** [Uniswap/uniswap-frontend#194]
Unique behaviour on Add Liquidity where Unlock re-appears on unlocked tokens upon deleting all ETH figures.

Replication process:

step 1: Unlock a token, wait for confirmed transaction

optional step: refresh page

step 2: enter ETH value if field is empty.

step 3: delete all figures in the ETH field.

Unlock appears once again for already unlocked token.

![unlockBack](http://jkrb.stream/misc/unlockBack.gif)

**Comment by haydenadams** [comment]
I can't replicate

**Comment by haydenadams** [comment]
@rossbulat okay nvm you're right. Gif helped.

**Comment by NoahZinsmeister** [comment]
this should be fixed in the beta branch
