### ISSUE TITLE
Estimated output on Send tab

### ISSUE THREAD

**Issue by rsrsyed** [Uniswap/uniswap-frontend#197]
On the "Send" page https://uniswap.exchange/send if you enter an input amount the UI does not show the estimated output. Since the "Swap" page shows it, I think it should be fairly easy to also show it on the "Send" page.

**Comment by haydenadams** [comment]
Not sure what you mean

<img width="780" alt="screen shot 2019-01-12 at 11 07 16 pm" src="https://user-images.githubusercontent.com/9343483/51081502-d7b3e880-16be-11e9-9a98-4ad529a643b8.png">
