### ISSUE TITLE
Rounding issues on the front-end

### ISSUE THREAD

**Issue by OliverNChalk** [Uniswap/uniswap-frontend#214]
On the front-end we round all the entries toFixed(7). This means we round up or down to the nears number. The problem here is that we could round the ETH input up, while the TOKEN output rounds down. This would result in a failed trade or addLiquidity if the user attempted to use all their tokens. 

For exmaple, if a user added liquidity to a pool and entered 1000 DAI, they could be setting up a transaction that needs 1000.00000000001... dai, resulting in a failure.

Here we can see the code rounding up or down:
![image](https://user-images.githubusercontent.com/11343499/51797346-dd9ee300-2201-11e9-920d-01ed8fe4b45f.png)

This happens again on lines 194 to 242:
![image](https://user-images.githubusercontent.com/11343499/51797351-ff986580-2201-11e9-872e-f3a30ab25a8b.png)

I have proposed a solution here (#213) and am looking to have it reviewed to ensure its correctness. In this solution, the users token input will likely change after they have edited. This is potentially a UX issue to keep in mind, however, I believe it was happening before anyway.

**Comment by NoahZinsmeister** [comment]
no more rounding in the beta branch :)
