### ISSUE TITLE
Exchange Between ERC20's on Kovan & Mainnet ETH.

### ISSUE THREAD

**Issue by aacostarua** [Uniswap/uniswap-frontend#219]
How would I go about setting an ERC20 on one one network to exchange into real main net ETH & transferred to that 'same' user.  Your guys product looks awesome & can't wait to test it out.  I'm going to be using this with a trust-wallet set up, so please let me know if its doable & what steps I might need to take.  I'd also like to know what value in src/components... is the token map:
const RINKEBY_TOKEN_MAP = {
7 | '0xDA5B056Cfb861282B4b59d29c9B395bcC238D29B': '0x0d8775f648430679a709e98d2b0cb6250d2887ef',
…
Thanks.

**Comment by A-w-K** [comment]
I don't think it is clear what you are trying to achieve. Are you suggesting to set up an exchange between Rinkeby and Mainnet?

**Comment by aacostarua** [comment]
Yes.  Between kovan and mainnet, but I assume it would work the same.

On Jan 28, 2019, at 8:19 AM, Alexander Kröll <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't think it is clear what you are trying to achieve. Are you suggesting to set up an exchange between Rinkeby and Mainnet?

**Comment by aacostarua** [comment]
I would like to know the what is suppose to go in /home/user1/Desktop/uniswap-frontend-master/src/ducks/addresses.js ... such as the fromToken & the exchangeAddresses part.  I'm trying to set a specific coin on testnet.

**Comment by aacostarua** [comment]
I also get "pip install -r requirements.txt
Collecting vyper==0.1.0b4 (from -r requirements.txt (line 1))
  Could not find a version that satisfies the requirement vyper==0.1.0b4 (from -r requirements.txt (line 1)) (from versions: )
No matching distribution found for vyper==0.1.0b4 (from -r requirements.txt (line 1))" when I try "pip install -r requirements.txt" after installing the rest of the necessary packages.

**Comment by aacostarua** [comment]
Yeah @haydenadams I figured.  I was wondering if someone could explain or point me to the solution in my error when trying to run that command.  Thanks.
