### ISSUE TITLE
Show details displays small amounts rounded to 0

### ISSUE THREAD

**Issue by kingjacob** [Uniswap/uniswap-frontend#223]
When adding small bits liquidity to a token like BTC, it displays that 1 pool token is worth 1 ETH + 0 BTC when it should display 1ETH + 0.031 BTC. Currently it rounds up to 0. 
 
<img width="550" alt="screen shot 2019-01-30 at 4 33 58 pm" src="https://user-images.githubusercontent.com/806312/52022379-8329af00-24ad-11e9-9220-b2a68a9a5545.png">

**Comment by NoahZinsmeister** [comment]
this should be fixed in the beta branch!
