### ISSUE TITLE
Token labels missing for some tokens on remove liquidity page

### ISSUE THREAD

**Issue by kingjacob** [Uniswap/uniswap-frontend#224]
A cursory search found MKR and DAI are missing labels, might be more only checked the ones on the main list.

<img width="567" alt="screen shot 2019-02-02 at 7 18 37 am" src="https://user-images.githubusercontent.com/806312/52165846-d9b80880-26ba-11e9-9973-d50173586f77.png">

**Comment by NoahZinsmeister** [comment]
this should be fixed!
