### ISSUE TITLE
Adjustable token allowance

### ISSUE THREAD

**Issue by phraktle** [Uniswap/uniswap-frontend#231]
When trying to create a new exchange or swapping from a token to ETH, the user is requested to approve an allowance for 100000000 tokens. Since users may not have such a high confidence in giving the contract such a large allowance, this should be exposed on the UI so that the user can set it to a comfortable level. (The current workaround is to create an allowance outside of the Uniswap UI).

**Comment by phraktle** [comment]
Also, a reasonable default for the allowance would be the amount entered in the buy/sell input field (if it's non-zero).

**Comment by NoahZinsmeister** [comment]
per #241, we are going to continue setting allowance to max unless at any point this is found to pose significant issues.

**Comment by bharathrao** [comment]
Some tokens don't allow setting approval more than what's available at the address. Uniswap can't be used for such tokens. Please enable user defined approval (with option for max 2^256)
