### ISSUE TITLE
Adjustable deadline

### ISSUE THREAD

**Issue by phraktle** [Uniswap/uniswap-frontend#232]
The UI currently sets a pretty short default deadline, which causes failed transactions. Users are not aware of there being a deadline for their transaction since this is not indicated on the UI, so they might set a low gas price that is bound to trigger the deadline. They also can't see the reason why the TX failed on Etherscan.

The UI should display what the deadline is for the transaction. It should also allow the user to adjust it.

**Comment by ChristophSiegenthaler** [comment]
I agree, I just wanted to write this myself since I also stumble into this one regulary.
