### ISSUE TITLE
ENS support

### ISSUE THREAD

**Issue by Arachnid** [Uniswap/uniswap-frontend#236]
It'd be great if the frontend supported ENS. There are two obvious places for this:

 1. When sending tokens, accept ENS names as destination addresses.
 2. When showing a user's account in the top right, do reverse resolution to show the account's ENS name where appropriate.

Happy to help with the integration in any way we can!

**Comment by haydenadams** [comment]
@Arachnid  Theres actually a better integration planned!

If you send eth to the fallback function is does an eth to token swap. Planning on setting up ETH to DAI swaps via dai.uniswap.eth, and MKR to ETH swaps via mkr.uniswap.eth, etc!

Accounts are interesting too!

**Comment by Arachnid** [comment]
That's a great idea! Likewise, let us know if we can help with that as well.

**Comment by OliverNChalk** [comment]
Hey Hayden, just wanted to clarify whether you mean 'MKR to ETH' or 'ETH to MKR' for the mkr.uniswap.eth address?

**Comment by haydenadams** [comment]
@OliverNChalk 

only eth has a fallback function - so ETH -> MKR

**Comment by gundas** [comment]
The payable fallback function does not allow specifying neither min_tokens nor deadline - it is an easy target for the front-runners.
There is already at least one bot front-running the uniswap transactions - https://etherscan.io/txs?a=0x54bc3fe4e8c377246acd5b4c25705c1b4324e859&p=1 , and without the min_tokens setting losses will be bigger.

**Comment by haydenadams** [comment]
@gundas Yup. This is only recommended for very very small trades right now.

**Comment by NoahZinsmeister** [comment]
ENS names are now first class citizens on the front-end! We may continue experimenting with the eth fallback functionality for dai.uniswap.eth/etc as well.

**Comment by Arachnid** [comment]
Excellent! Where can we find a good quality logo to add to the ENS front page?

**Comment by NoahZinsmeister** [comment]
cc @haydenadams ^

**Comment by haydenadams** [comment]
![Uniswap_icon_white](https://user-images.githubusercontent.com/9343483/58736112-a8cab480-83ca-11e9-8fa7-5f7f6ba12a5d.jpeg)
