### ISSUE TITLE
Don't require MetaMask to browse.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-frontend#239]
The UI should default to using a public facing Ethereum node for users who do not have MetaMask installed so they can browse the site, look at exchange rates, etc. without having to install MetaMask.  A warning banner can be presented at the top of the page letting them know that functionality will be limited, and the submit button can be disabled.  For uniswap.exchange, there is a single button on the page that actually requires MetaMask, every other feature of the app can be accomplished with a public Ethereum node.

**Comment by NoahZinsmeister** [comment]
totally! working on a fix for this, see #255

**Comment by NoahZinsmeister** [comment]
this is fixed!
