### ISSUE TITLE
Don't require account access to browse the app.

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-frontend#240]
When you load uniswap.exchange, the page does not function until the user gives the website access to the MetaMask account.  There is no need for account access until the user tries to submit, so there is no reason to demand the user give up their privacy until that point.

If there is functionality that depends on account access (such as a balance display), then a warning banner can alert the user that until they give access, functionality will be limited.  You can see an example of this at https://liquid-long.keydonix.com/.  When you first load the page, it will warn you that functionality will be limited until the user gives access, and it gives them something to click to make that happen now.  However, all of the page's functionality that can be done without account access is made available while in this state.  If the user tries to submit a transaction, it will then prompt for account access at that point, if the user hasn't already given access.

**Comment by NoahZinsmeister** [comment]
this is fixed! there may still be some rough edges to the connection flow, but these will be cleaned up in the coming weeks/months,
