### ISSUE TITLE
Pending swap and tab closed

### ISSUE THREAD

**Issue by davidullo** [Uniswap/uniswap-frontend#244]
Hi, I just tried to exchange 2.6 USDC with ETH and my swap was in a "pending" state, now I closed the tab of my mobile wallet and my USDC disappeared from it but I haven't received any ETH, should I wait for something to happen or did I lose my 2 dollars? Thanks in advance

**Comment by ChristophSiegenthaler** [comment]
I think this can be closed as it all worked: https://www.reddit.com/r/UniSwap/comments/azghyo/pending_swap_and_tab_closed/
