### ISSUE TITLE
Connect request rejection ignored

### ISSUE THREAD

**Issue by brunobar79** [Uniswap/uniswap-frontend#255]
Once you arrive to uniswap for the first time, you get the prompt to connect your Ethereum account (as per EIP-1102).  The problem is that after rejecting access (clicking "CANCEL" in the MetaMask popup), you get prompted again continuously.

DEMO: 

![demo](https://user-images.githubusercontent.com/1247834/55753127-94e08300-5a17-11e9-9b85-7581f15132fb.gif)

**Comment by NoahZinsmeister** [comment]
@brunobar79 working on a fix for this as we speak! thanks for the issue, will ping when the feature is released in beta/prod. we're going to be using infura to back data requests until a wallet is required.

**Comment by NoahZinsmeister** [comment]
this is fixed! there may still be some rough edges to the connection flow, but these will be cleaned up in the coming weeks/months,
