### ISSUE TITLE
tokenOwnerAddress causes failure when changing the default currency

### ISSUE THREAD

**Issue by PaulRBerg** [Uniswap/uniswap-frontend#258]
## Description

I'm using the following Uniswap components in my project:

- CurrencyInputPanel
- TokenLogo

To use them, I had to import a few things, such as the `web3connect` redux duck. This is where the problem is. If I swap all the initial values from `ETH` to `DAI`, I get the following error:

> Unhandled Rejection (Error): invalid address (arg="_owner", coderType="address", value="", version=4.0.27)

(I made sure I'm using the same version of web3)

React tells me the issue is at this line:

```javascript
tokenOwner.forEach(async (spenderAddress) => {
```

But because that's an anonymous function, it's been a bit tricky to track the error to an exact line in the source code.

I debugged this for quite a while and it turns out the issue is here:

```javascript
const balance = await contract.methods.allowance(tokenOwnerAddress, spenderAddress).call();
```

Because I set an ERC20 token as the default currency and not `ETH`, the `sync` function won't stop at this line:

```javascript
if (tokenAddress === "ethereum") {
    return;
}
```
Therefore it will erroneously try to call a contract method with an invalid `tokenOwnerAddress` (redux runs before the web3 provider return the account).

## Environment

- macOS Mojave 10.14.2
- npm 6.9.0
- node 10.15.3

**Comment by NoahZinsmeister** [comment]
this is fixed in the beta branch!
