### ISSUE TITLE
Inverted exchange rate

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#272]
Some people have requested the ability to view ETH/ERC20 in addition to ERC20/ETH

USD values are also something to consider here.

**Comment by OliverNChalk** [comment]
I find this [implementation](https://uniswap.ch/swap) to be quite convenient. Would recommend for inverted rates. As far as USD pricing goes, I think most will look to the USD cost of the token they are buying, so maybe attaching a bracketed USD pricing like this could help:

![image](https://user-images.githubusercontent.com/11343499/56860155-924dc980-69d6-11e9-8538-19d0fae487bb.png)

**Comment by NoahZinsmeister** [comment]
Closing as inverted rates can be seen by clicking the rate. Future designs will incorporate more explicit inverted rates (we should feel free to make another issue for this if we want!).
