### ISSUE TITLE
Add HUM token

### ISSUE THREAD

**Issue by fafrd** [Uniswap/uniswap-frontend#286]
**Please provide the following information for your token.**

Token Address: 0xbbd1706d16418bb136e1497a73d3af4164586da0
Token Name (from contract): Humanity
Token Decimals (from contract): 18
Token Symbol (from contract): HUM
Uniswap Exchange Address of Token: 0xE499657190D515119077aF5D64F44b6f850BaEa5

Link to the official homepage of the token: https://www.humanitydao.org/

**Comment by KyleJKistner** [comment]
Was this closed on accident?

**Comment by NoahZinsmeister** [comment]
sorry, yes, we'll be monitoring token requests via open issues

**Comment by martinkrung** [comment]
you can add it yourself to src/contexts/Tokens.js  and then make a pull request, as example see my pull request:

https://github.com/Uniswap/uniswap-frontend/pull/290

**Comment by KyleJKistner** [comment]
> you can add it yourself to src/contexts/Tokens.js and then make a pull request, as example see my pull request:
> 
> #290

![image](https://user-images.githubusercontent.com/14222111/58388978-d6db7d80-7ff3-11e9-95dd-72f225099bd0.png)

**Comment by fafrd** [comment]
I'd still like to have this token added to the uniswap frontend.

Is there anything further I should do? @NoahZinsmeister

**Comment by osyed** [comment]
@fafrd your token is automatically listed on UniswapDEX.com if it has at least 1 ETH of liquidity. You can also use this link to send users directly to your token page.
https://uniswapdex.com/?token=0xbBd1706d16418bb136e1497A73d3af4164586DA0

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
