### ISSUE TITLE
Add Dev Token

### ISSUE THREAD

**Issue by aggre** [Uniswap/uniswap-frontend#289]
**Please provide the following information for your token.**

Token Address: `0x98626E2C9231f03504273d55f397409deFD4a093`
Token Name (from contract): `Dev Token`
Token Decimals (from contract): `18`
Token Symbol (from contract): `DEV`
Uniswap Exchange Address of Token: `0x48b109a5981573d03e5becec76aa805b7640cd58`

Link to the official homepage of the token: https://devtoken.rocks/

**Comment by martinkrung** [comment]
you can add it yourself to src/contexts/Tokens.js  and then make a pull request, as example see my pull request:

https://github.com/Uniswap/uniswap-frontend/pull/290

**Comment by NoahZinsmeister** [comment]
please don't submit PRs for token additions, we will be monitoring requests only via issues.

**Comment by osyed** [comment]
@aggre your token is automatically listed on UniswapDEX.com if it has at least 1 ETH of liquidity. You can also use this link to send users directly to your token page.
https://uniswapdex.com/?token=0x98626E2C9231f03504273d55f397409deFD4a093

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
