### ISSUE TITLE
add GRG token

### ISSUE THREAD

**Issue by gabririgo** [Uniswap/uniswap-frontend#294]
Token Address: 0x4fbb350052bca5417566f188eb2ebce5b19bc964
Token Name (from contract): Rigo Token
Token Decimals (from contract): 18
Token Symbol (from contract): GRG
Uniswap Exchange Address of Token: 0xee5e8D2357A29F4a85a938679233fE24fbC2cf1D

Link to the official homepage of the token: https://rigoblock.com

**Comment by osyed** [comment]
@gabririgo your token is automatically listed on UniswapDEX.com if it has at least 1 ETH of liquidity. You can also use this link to send users directly to your token page.
https://uniswapdex.com/?token=0x4FbB350052Bca5417566f188eB2EBCE5b19BC964

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
