### ISSUE TITLE
Add GEN token

### ISSUE THREAD

**Issue by leviadam** [Uniswap/uniswap-frontend#296]
**Please provide the following information for your token.**

Token Address: 0x543ff227f64aa17ea132bf9886cab5db55dcaddf
Token Name (from contract): DAOstack
Token Decimals (from contract): 18
Token Symbol (from contract): GEN
Uniswap Exchange Address of Token: 0x26Cc0EAb6Cb650B0Db4D0d0dA8cB5BF69F4ad692

Link to the official homepage of the token: [daostack.io](https://daostack.io)

**Comment by NoahZinsmeister** [comment]
added!

**Comment by leviadam** [comment]
Thank you!
Can you also add the logo?

https://daostack.io/DAOstack_Glyph_300.svg

**Comment by NoahZinsmeister** [comment]
already there, we get our logos from https://github.com/TrustWallet/tokens

![image](https://user-images.githubusercontent.com/3760414/58730911-68176f00-83bb-11e9-8708-f5599c038971.png)

**Comment by leviadam** [comment]
Wow, that is weird. The logo there is not correct.
I just opened a PR to correct it. https://github.com/TrustWallet/tokens/pull/1738

Thank you!
