### ISSUE TITLE
swap amount always set to 0 with Chrome MetaMask 

### ISSUE THREAD

**Issue by yurenji** [Uniswap/uniswap-frontend#300]
**Bug Description**
Transaction amount is always set to 0 no matter what amount I set. 

**Steps to Reproduce**
1. open uniswap in Chrome browser
2. select DAI and set an amount to swap to ETH. 
3. click Swap button will trigger the MetaMask popup page
4. The amount on MetaMask popup page is always 0 

**Expected Behavior**
The amount on MetaMask popup page should equal the amount on previous page

![image](https://user-images.githubusercontent.com/5565266/58071849-79e55f00-7bd0-11e9-96f3-b0ec8a25d273.png)

**Comment by haydenadams** [comment]
@yurenji The amount shown by metamask is the amountof ETH sent to the exchange contract. Since you are trading DAI for ETH that should be 0.

The trade will work!

**Comment by yurenji** [comment]
@haydenadams thanks for the explanation!
