### ISSUE TITLE
Incorrect computation of liquidity pool share

### ISSUE THREAD

**Issue by adamskrodzki** [Uniswap/uniswap-frontend#305]
Hi,
I've send 14 ETH and 105588 POA20 to liquidity pool

https://etherscan.io/tx/0x8fbe6358dccb7680cba068f6da17c62ab60cd7b516fb9f3348c0479c8a82415a 

Why my share in liquidity pool is calculated as 

13.1 ETH + 105588.3141 POA20 

where 0.9  EHT dissapeared ?

**Comment by adamskrodzki** [comment]
There is something wrong with rounding numbers, take a look at screenshots, how very small change in token Amount caused rapid change in ETH pool share

![image](https://user-images.githubusercontent.com/10146412/58367492-4102fe00-7ee0-11e9-9eff-cc043a62a17a.png)

**Comment by haydenadams** [comment]
very old issue I'm assuming this is fixed
