### ISSUE TITLE
Add AMN token

### ISSUE THREAD

**Issue by julesGoullee** [Uniswap/uniswap-frontend#307]
Token Address: 0x737f98ac8ca59f2c68ad658e3c3d8c8963e40a4c
Token Name (from contract): Amon
Token Decimals (from contract): 18
Token Symbol (from contract): AMN
Uniswap Exchange Address of Token: 0xE6C198d27a5B71144B40cFa2362ae3166728e0C8

Link to the official homepage of the token: [amon.tech](https://amon.tech)

**Comment by haydenadams** [comment]
@julesGoullee There is only $1000 worth of liquidity in the pool which limits trades to around $5-10 

Linking users to http://uniswap.exchange/swap/0xE6C198d27a5B71144B40cFa2362ae3166728e0C8
 will allow them to trade AMN but it is not liquid enough to be added to the default list

**Comment by julesGoullee** [comment]
Ok, I can put more if you think we need it if looks https://coinmarketcap.com/currencies/amon we don't have high volume, how much you advise me to put inside relate to our liquidity?

**Comment by julesGoullee** [comment]
@haydenadams ?

**Comment by julesGoullee** [comment]
Hey guys, @haydenadams @NoahZinsmeister I just wanna know how much could be good to start the exchange from your point of view

**Comment by osyed** [comment]
@julesGoullee your token is automatically listed on UniswapDEX.com if it has at least 1 ETH of liquidity. You can also use this link to send users directly to your token page.
https://uniswapdex.com/?token=0x737F98AC8cA59f2C68aD658E3C3d8C8963E40a4c

**Comment by julesGoullee** [comment]
Hi Guys,
we have added some liquidity so we should be ready to go.
@NoahZinsmeister @haydenadams
