### ISSUE TITLE
Unable to add liquidity to the PLR exchange

### ISSUE THREAD

**Issue by vitorpy** [Uniswap/uniswap-frontend#320]
**Bug Description**

I've created an exchange for the PLR token (0xe3818504c1b32bf1557b16c238b2e01fd3149c17). When tried to add liquidity the button "Add Liquidity" doesn't appear to work and, observing the JS console, I can see a message "gas required exceeds allowance or always failing transaction". 

I've tried both MetaMask and Dapper as w3 providers but the error seems to happen on both of them.

**Steps to Reproduce**
1. Pre-load MetaMask, or other w3 provider, with some PLR and ETH.
2. Go to Uniswap, tap on Pool, Add Liquidity
3. Pick some amounts
4. Tap on unlock
5. After the transaction is confirmed, tap on Liquidity
6. Observe JS console to see the error message

**Expected Behavior**

To create a contract call transferring funds to the liquidity pool and minting the appropriate number of liquidity tokens.

**Additional Context**
![image](https://user-images.githubusercontent.com/12871/58892014-6b756800-86e5-11e9-9511-251654f749e1.png)

Screenshot above on both Dapper and MetaMask as w3 providers. I've also tried different configurations (Firefox, a Linux laptop, ...). As far I'm able to investigate, the environment doesn't affect the issue.

**Comment by NoahZinsmeister** [comment]
@vitorpy hm i can't reproduce with other tokens. are you open to sending me 1 or 2 PLR for testing purposes at noah.zinsmeister.eth? is there anything non-standard in the PLR token contract that might be causing an error?

**Comment by NoahZinsmeister** [comment]
ah. @vitorpy looks like the PLR token suffers from the infamous [return value bug](https://medium.com/coinmonks/missing-return-value-bug-at-least-130-tokens-affected-d67bf08521ca). unfortunately, this means that the token is technically not compliant with ERC-20 standard, and can't be used with the current version of the uniswap factory.
