### ISSUE TITLE
Add LEAP token

### ISSUE THREAD

**Issue by johannbarbie** [Uniswap/uniswap-frontend#324]
**Please provide the following information for your token.**

Token Address: 0x78230e69d6e6449db1e11904e0bd81c018454d7a
Token Name (from contract): LeapToken
Token Decimals (from contract): 18
Token Symbol (from contract): LEAP
Uniswap Exchange Address of Token: 0xb5e62826970f6b66ad3084d5f77970626be62a99

Link to the official homepage of the token: https://leapdao.org

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
