### ISSUE TITLE
Allow specifying outputCurrency by a URL parameter

### ISSUE THREAD

**Issue by safareli** [Uniswap/uniswap-frontend#327]
We (@f-o-a-m) are going to embed `https://uniswap.exchange/swap` using an iframe in our app as a modal, so people can buy tokens without leaving the app. But users will have to chose the [`outputCurrency`](https://github.com/Uniswap/uniswap-frontend/blob/beta/src/pages/Swap/index.js#L130) by hand, all the time. It would be great if something like this `https://uniswap.exchange/swap?outputCurrency=FOAM` resulted in auto selecting of the `outputCurrency` to FOAM.

**Comment by NoahZinsmeister** [comment]
hey @safareli / @f-o-a-m, i have good and bad news:

the good news: i have outputCurrency autofilling based on URL parameters in the localhost version of #329.

the bad news: there's a weird interaction between react router + netlify that is breaking the redirection in the deployed version, and i haven't figured out how to fix it yet.

unfortunately the PR is blocked until i can figure this out, so either hang tight, or feel free to take a look, another pair of eyes can't hurt.

**Comment by NoahZinsmeister** [comment]
update, [tracking this with netlify](https://community.netlify.com/t/spa-rewrite-inconsistencies/1422)

**Comment by NoahZinsmeister** [comment]
@safareli just added this feature to our beta release! would you mind testing it with your iframe setup? the URL for FOAM is [https://beta.uniswap.exchange/swap/0x4946Fcea7C692606e8908002e55A582af44AC121](https://beta.uniswap.exchange/swap/0x4946Fcea7C692606e8908002e55A582af44AC121). if all goes well we will merge this into the production branch shortly.

**Comment by safareli** [comment]
I have tested and It works! When is the actual release planed to be shipped? If it's not know yet, It would be great if you can ping me here so we start using this.

Thanks 🎉!

**Comment by NoahZinsmeister** [comment]
@safareli it's live! [https://uniswap.exchange/swap/0x4946Fcea7C692606e8908002e55A582af44AC121](https://uniswap.exchange/swap/0x4946Fcea7C692606e8908002e55A582af44AC121)
