### ISSUE TITLE
Add NUSD token

### ISSUE THREAD

**Issue by njinchen** [Uniswap/uniswap-frontend#328]
**Please provide the following information for your token.**

Token Address: 0x0c6144c16af288948c8fdb37fd8fec94bff3d1d9
Token Name (from contract): Neutral
Token Decimals (from contract): 6
Token Symbol (from contract): NUSD
Uniswap Exchange Address of Token: 0xce23d871009a52ab5560ba613a042e45e1f33539

Link to the official homepage of the token: neutralproject.com

**Comment by osyed** [comment]
@njinchen your token is automatically listed on UniswapDEX.com if it has at least 1 ETH of liquidity. You can also use this link to send users directly to your token page.
https://uniswapdex.com/?token=0x0C6144c16af288948C8fdB37fD8fEc94bfF3d1d9

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
