### ISSUE TITLE
Add 3 Set Protocol Tokens - ETHLOVOL / BTCLOVOL / BTCETH5050

### ISSUE THREAD

**Issue by richardliang** [Uniswap/uniswap-frontend#330]
**Please provide the following information for your token.**

Token Address: 0xc06aec5191be16b94ffc97b6fc01393527367365
Token Name (from contract): BTC ETH Equal Weight Set
Token Decimals (from contract): 18
Token Symbol (from contract): BTCETH5050
Uniswap Exchange Address of Token: 0x539f7952f7b21c48aff332cd5d9cf6e28eba290f

Link to the official homepage of the token: https://www.tokensets.com/set/btceth5050

Token Address: 0x585c2cf94c41b528ec7329cbc3cde3c4f8d268db
Token Name (from contract): ETH Range Bound Low Volatility (name in our contract is different from backend)
Token Decimals (from contract): 18
Token Symbol (from contract): ETHLOVOL (symbol in our contract is different from backend)
Uniswap Exchange Address of Token: 0x10c4be5806878f78e6179af6d09d035bbdab2ec2

Link to the official homepage of the token: https://www.tokensets.com/set/ethlovol

Token Address: 0x20649d97b1393105cf92a5083fd2aff7c99ebe56
Token Name (from contract): BTC Range Bound Low Volatility (name in our contract is different from backend)
Token Decimals (from contract): 18
Token Symbol (from contract): BTCLOVOL(symbol in our contract is different from backend)
Uniswap Exchange Address of Token: 0xe2e496e3fc550b68feeeddad7db42d7063e6729e

Link to the official homepage of the token: https://www.tokensets.com/set/btclovol

**Comment by haydenadams** [comment]
@richardliang are you from set protocol by any chance? or just interested in uniswap supporting set protocol tokens

**Comment by richardliang** [comment]
> @richardliang are you from set protocol by any chance? or just interested in uniswap supporting set protocol tokens

hey @haydenadams yeah, i'm from set protocol. was interested in adding some sets to uniswap but not those 3 above anymore

**Comment by haydenadams** [comment]
@richardliang 

cool! Would you be interested in chatting some time? Would love to talk more to your team to make sure I understand how Set works and if there are any additional implications to think about here

If so, drop me an email :) 

hayden@uniswap.io
