### ISSUE TITLE
Add XD Token

### ISSUE THREAD

**Issue by bhusheth** [Uniswap/uniswap-frontend#331]
**Please provide the following information for your token.**

Token Address: 0x24dcc881e7dd730546834452f21872d5cb4b5293
Token Name (from contract): Data Transaction Token
Token Decimals (from contract): 18
Token Symbol (from contract): XD
Uniswap Exchange Address of Token: 0xb7cf1e1ea55572713feeec025d7cf56b3c6c6b6d

Link to the official homepage of the token: https://datatxtoken.com/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
