### ISSUE TITLE
Add RING token

### ISSUE THREAD

**Issue by HackFisher** [Uniswap/uniswap-frontend#333]
**Please provide the following information for your token.**

Token Address: 0x9469d013805bffb7d3debe5e7839237e535ec483
Token Name (from contract): Evolution Land Global Token
Token Decimals (from contract): 18
Token Symbol (from contract): RING
Uniswap Exchange Address of Token: 0xebd8aa50b26bfa63007d61eba777a9dde7e43c64

Link to the official homepage of the token: http://www.evolution.land

**Comment by ashleigh-schap** [comment]
This is a duplicate request for RING token
