### ISSUE TITLE
App not loading without unlocked mainnet account

### ISSUE THREAD

**Issue by marceljay** [Uniswap/uniswap-frontend#337]
Strangely, in a local version of the frontend, the interface would not appear before logged into MetaMask with Mainnet selected. Next to the logo I only see the spinning loading overlay. On uniswap.exchange though, the problem does not exist and there is even a modal showing the wrong network etc.

I ran yarn build and start on the beta branch. I ran the app from a Win10 machine through bash/WSL.

**Comment by marceljay** [comment]
I guess this can be closed now. Without a provider specified in .env.local, the app won't load. Maybe there could be some hint in the docs or in the UI.

**Comment by NoahZinsmeister** [comment]
> Rename .env.local.example to .env.local and fill in the appropriate variables.

It's in the README.md in this repo.

**Comment by marceljay** [comment]
I read that, yet I was not aware a provider hat specified exactly there to make the app run. The sentence is not really self-explanatory.
