### ISSUE TITLE
Add Dragonereum Gold token

### ISSUE THREAD

**Issue by maksim-tolo** [Uniswap/uniswap-frontend#343]
Token Address: 0x150b0b96933B75Ce27af8b92441F8fB683bF9739
Token Name (from contract): Dragonereum Gold
Token Decimals (from contract): 18
Token Symbol (from contract): GOLD
Uniswap Exchange Address of Token: 0x7b1C3192eFa401eA37951feDC8007BcbEc2DBB6d
Link to the official homepage of the token: https://dragonereum.io/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
