### ISSUE TITLE
Add PHT (Photochain) Token 

### ISSUE THREAD

**Issue by Vandal38** [Uniswap/uniswap-frontend#348]
**Please provide the following information for your token.**

Token Address: 0x88652845a5495983b70aebbf25102361552d5e54
Token Name (from contract): Photochain Token
Token Decimals (from contract): 18
Token Symbol (from contract): PHT
Uniswap Exchange Address of Token: 0x213988470530c2c098E6f22F15437930CDBCca26

Link to the official homepage of the token:https://photochain.io/

**Comment by xorred** [comment]
+1 vote

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
