### ISSUE TITLE
Add COS (COSS) Token

### ISSUE THREAD

**Issue by Omer-Shukrullah** [Uniswap/uniswap-frontend#349]
**Please provide the following information for your token.**

Token Address: 0x7d3cb11f8c13730c24d01826d8f2005f0e1b348f
Token Name (from contract): COS
Token Decimals (from contract): 18
Token Symbol (from contract): COS
Uniswap Exchange Address of Token: 0x7F9A00BB057424b9B1382591cfb8761d9B08a434

Link to the official homepage of the token: https://cossgroup.com

**Comment by haydenadams** [comment]
As far as I can tell this is the official token https://etherscan.io/token/0x9e96604445ec19ffed9a5e8dd7b50a29c899a10c

**Comment by Omer-Shukrullah** [comment]
That is actually the old token contract address. COSS exchange just underwent a merger where COSS token and LALA were combined to make COS token. The contract address I've provided is actually for the new merged token.

**Comment by yinzeus** [comment]
background: https://medium.com/@coss.io/the-worlds-first-token-merger-what-s-in-it-for-you-4eabdc6743f

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
