### ISSUE TITLE
Add DIP (Etherisc) token

### ISSUE THREAD

**Issue by pascalvanhecke** [Uniswap/uniswap-frontend#359]
**Please provide the following information for your token.**

Token Address: 0xc719d010B63E5bbF2C0551872CD5316ED26AcD83
Token Name (from contract): Decentralized Insurance Protocol
Token Decimals (from contract): 18
Token Symbol (from contract): DIP
Uniswap Exchange Address of Token: 0x61792F290e5100FBBcBb2309F03A1Bab869fb850

Link to the official homepage of the token: https://etherisc.com/

Additional info: 
- Previously submitted as a pull request https://github.com/Uniswap/uniswap-frontend/pull/356
- Team had first dApp live end of 2016 https://www.youtube.com/watch?v=ED1-HaWEnRs
- respected in the community, organizers of decentralized insurance conferences https://d1conf.com/ and lots of public speaking see https://www.youtube.com/watch?v=qQalYZJAulU and https://www.youtube.com/watch?v=VsQw21cV680 with Hayden
- Strong team (2 people from EF among advisors https://etherisc.com/#team ), but Token only available on Dexes similar to Rocket Pool https://github.com/Uniswap/uniswap-frontend/commit/b8035fc82f01f5bd44d1513ce3fd23df03a710e0

**Comment by martinkrung** [comment]
And there is also a LP with 27.4058 ETH + 438433.0961 dip right now
