### ISSUE TITLE
[TOKEN REQUEST] Add Market Protocol Token(MKT)

### ISSUE THREAD

**Issue by travisdmathis** [Uniswap/uniswap-frontend#360]
**Please provide the following information for your token.**

Token Address: 0xba23485a04b897c957918fde2dabd4867838140b/
Token Name (from contract): Market Protocol Token
Token Decimals (from contract): 18
Token Symbol (from contract): MKT
Uniswap Exchange Address of Token: 0x7d6fa7b0a7dec3c0758f0b57bb446f4cee70d330

Link to the official homepage of the token: https://marketprotocol.io / https://mpexchange.io

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
