### ISSUE TITLE
Add MLN Token

### ISSUE THREAD

**Issue by martinkrung** [Uniswap/uniswap-frontend#367]
Token Address: 0xec67005c4e498ec7f55e092bd1d35cbc47c91892
Token Name (from contract): Melon Token 
Token Decimals (from contract): 18
Token Symbol (from contract):  MLN
Uniswap Exchange Address of Token: 0xa931f4eb165ac307fd7431b5ec6eadde53e14b0c

Link to the official homepage of the token: https://melonport.com

**Comment by fabtho** [comment]
MLN has no token icon: https://uniswap.exchange/swap/0xec67005c4e498ec7f55e092bd1d35cbc47c91892 

Whats the source of this icons? Is it on https://github.com/TrustWallet/tokens?

**Comment by mounibec** [comment]
You can use this https://cdn.jsdelivr.net/gh/atomiclabs/cryptocurrency-icons@95af504a411054bbd7a2fb97a84a2c2831d334cc/128/color/mln.png from http://cryptoicons.co/

**Comment by fabtho** [comment]
Thanks, but im not sure if this is still the right one.
See my question here:
"Whats the official MLN token icon? Is it the M oder the strange dice thing?" Source: https://twitter.com/martinkrung/status/1153244982737870849

**Comment by haydenadams** [comment]
@fabtho yeah Uniswap icons are pulled from that trust repo
