### ISSUE TITLE
Update Exchange Addresses

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#37]
Exchange addresses here are all outdated and won't work: 
https://github.com/Uniswap/uniswap-frontend/blob/master/src/ducks/addresses.js

Token addresses should be the same. Here are the new exchange addresses on Rinkeby: 

BAT
Token: 0xDA5B056Cfb861282B4b59d29c9B395bcC238D29B
Exchange: 0x9B913956036a3462330B0642B20D3879ce68b450

DAI
Token: 0x2448eE2641d78CC42D7AD76498917359D961A783
Exchange: 0x77dB9C915809e7BE439D2AB21032B1b8B58F6891

MKR
Token: 0xF9bA5210F91D0474bd1e1DcDAeC4C58E359AaD85
Exchange: 0x93bB63aFe1E0180d0eF100D774B473034fd60C36

OMG
Token: 0x879884c3C46A24f56089f3bBbe4d5e38dB5788C0
Exchange: 0x26C226EBb6104676E593F8A070aD6f25cDa60F8D

ZRX
Token: 0xF22e3F33768354c9805d046af3C0926f27741B43
Exchange: 0xaBD44a1D1b9Fb0F39fE1D1ee6b1e2a14916D067D

**Comment by chikeichan** [comment]
Fixed by 750a29e967044de68f79eed14fc53e5af329c273
