### ISSUE TITLE
Add GZE

### ISSUE THREAD

**Issue by apguerrera** [Uniswap/uniswap-frontend#373]
**Please provide the following information for your token.**

Token Address:
0x4ac00f287f36a6aad655281fe1ca6798c9cb727b

Token Name (from contract):
GazeCoin Metaverse Token

Token Decimals (from contract): 18
Token Symbol (from contract): GZE
Uniswap Exchange Address of Token:
0x6171aa1829c9f9479206658de3b6df4fa48f82c0

Link to the official homepage of the token:
https://www.gazecoin.io/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time as the liquidity is too low, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
