### ISSUE TITLE
 Add JSE Token

### ISSUE THREAD

**Issue by jamesbachini** [Uniswap/uniswap-frontend#379]
**Please provide the following information for your token.**

Token Address: 0x2d184014b5658c453443aa87c8e9c4d57285620b
Token Name (from contract): JSE Token
Token Decimals (from contract): 18
Token Symbol (from contract): JSE
Uniswap Exchange Address of Token: 0xa248A46b97204b6F4D5B05ba824FBea46390D978

Link to the official homepage of the token: https://jsecoin.com

**Comment by JohnRSim** [comment]
Hey guys any followup needed - many thanks

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
