### ISSUE TITLE
Token Modal Rework

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-frontend#382]
The current token modal could use some love!

Let's use this issue to track progress on the rework, which consists mainly of UI improvements and increased data density per offline discussions/figma designs.

Completion should close #145 and #235.

**Comment by callil** [comment]
Current design proposal: https://www.figma.com/file/EKGIDMFG22P1J0mbJUFKbrcF/Token-List?node-id=28%3A0

**Comment by NoahZinsmeister** [comment]
Let's flesh out details like data fetching, local storage designs for per-user custom tokens, etc. here as they come up!

**Comment by ianlapham** [comment]
Which dropdown design are we leaning towards? I'm thinking about going with this one as a touch up to start 
![Screen Shot 2019-07-30 at 12 34 53 PM](https://user-images.githubusercontent.com/17100331/62147844-73591f00-b2c6-11e9-8215-d689fdf2d39c.png)

**Comment by callil** [comment]
@ianlapham I think thats a fine starting place. These are the core UX features we will have to build to achieve the more enhanced design as linked above.

- [ ] Auto focus text input
- [ ] Arrow through list and Enter to select
- [ ] Text input filters by token ticker, name, and full addresses

Listing order:
Tokens with user balance
Added Tokens with user balance 
Added Tokens without balance
Tokens by 24h Volume

**Comment by NoahZinsmeister** [comment]
as far as data fetching goes: for now let's implement the design without data (though probably with dummy localhost data, just to see structurally how it would be added in), and then try to add 1 piece of data at a time.

the easiest to start with, IMO, would be 24h volume for each token, fetched from the graph. as a fallback, i propose that if the graph is unavailable, we fetch current liquidity pool size (eth balance) for each token exchange using direct on-chain calls.

a bit harder is token balances. we'd probably have to fetch these on-chain, once per address/token.

some considerations in both cases:
a) when do we fetch the data (on page load? on modal load?)
b) how do we/do we even try to keep things up to date. we definitely can't loop through every address/token/etc. every block, so we'll have to think through this a bit...the story is probably simpler with the graph (we can just use a graphql subscription) than with on-chain stuff

**Comment by ianlapham** [comment]
Good points - so before i get any further, is there any version we'd want to commit to beta that is just a UI change (no data)? 

Currently implementing balance fetching. Definitely don't want to update those balances every block - we could query balances on page load and then update when they open modal? (Just so some data is immedietly avaialble on modal render). 

I have been doing on chain requests for balances, but let me see if the graph makes this easier.

**Comment by NoahZinsmeister** [comment]
@ianlapham i think before committing to beta we'd want at least 1 piece of data in addition to the UI changes.

re. fetching balances on-chain: i'd be interested to see if the app takes a noticeable hit if we fetch all balances on page load. one option would be to do the initial fetch on page load, and then run an update loop for all tokens that we know the user has an existing balance of every `x` seconds, and potentially even run a full update every `y`th iteration of this loop. thoughts?

re. the graph, it's probably worthwhile to see if they have a solution for user token balances, but even if they do i think it makes sense to have an on-chain version as a backstop.

**Comment by ianlapham** [comment]
Yep so i might as well implement the on-chain fetch first because we'll need it anyways as plan b for the graph. 

I'm going to try a couple variations (starting with everything on page load) and see how the app responds.

**Comment by NoahZinsmeister** [comment]
closed by #399! big props to @ianlapham
