### ISSUE TITLE
Improved URL Linking

### ISSUE THREAD

**Issue by NoahZinsmeister** [Uniswap/uniswap-frontend#383]
The current linking setup leaves something to be desired. This issue will track progress on the following design:

# Description
In the `/swap` and `/send` tabs, users should be able to add a variety of arguments to a query string that pre-fills values in the UI.

# Requirements
1. Variables that should be included (naming tentative): `inputCurrency`, `outputCurrency`, `exactField` (input or output), `exactAmount` (input or output), `slippage`, `recipient` (only in `/send`)
2. These variables should be treated as follows: on page load, all query string arguments should be parsed. After throwing out arguments with invalid/unrecognized keys, the arguments with valid keys should be passed down into the respective component, and run through the same validation as if a user had simply typed/selected them (for the most part, this should be as simply as setting them as the initial state). 
3. Documentation of all available query string options should be added to the `README.md`

# Open Questions
1. Should all/some variables should persist in the URL?
2. Should variables in the UI be synced to the URL?
3. As a stretch goal, let's try to persist the selected token(s) across `/send` and `/swap` per #235.

Note: Completion of this issue should close #355 and #160.

**Comment by ianlapham** [comment]
- [ slippage]

**Comment by ianlapham** [comment]
- [ ] slippage
- [ ] input currency
