### ISSUE TITLE
Add invert icon to exchange rate and add sigfigs

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-frontend#386]
We should default to displaying the inverted rate and change the copy to say "Price" or "Current Price" to align with exchange and tracker standards.

Add small icon to help people understand they can click to invert the rate.

**Comment by NoahZinsmeister** [comment]
@callil is the default (inverted) rate that you want `1 <outputToken> = X <inputToken>`? that's what we changed it to in beta.

or, do you want it to be `1 <estimatedToken> = X <exactToken>?` this would display `1 <outputToken> = X <inputToken>` by default if a user a) picks an output token, then b) types an input amount (of ETH). however, it would flip to the other rate if they then c) edit the output amount

**Comment by NoahZinsmeister** [comment]
totally agreed re. copy and icon

**Comment by callil** [comment]
Adding to this issue re: discord feedback -- prices should show significant figures 

```
SNX pricing is usually at 7 decimal places
This is shown on uniswap: 
1 SNX = 0.0011 ETH
```

**Comment by haydenadams** [comment]
4 sig figs with I think a floor of 6 decimal places. Debatably 5

**Comment by haydenadams** [comment]
.00005 ETH is $0.01 for context
