### ISSUE TITLE
Mobile response when details open

### ISSUE THREAD

**Issue by ianlapham** [Uniswap/uniswap-frontend#387]
Right now when users open transaction details on mobile the container widths grow suddenly. 

Lets fix it so opening is smoother and widths are consistent.

**Comment by NoahZinsmeister** [comment]
my fairly strong preference for stuff like this is to use react-spring (see e.g. https://codesandbox.io/embed/lp80n9z7v9). i think it makes the most sense for these types of open/close interactions, see the modal component for example.

css animations do make sense for certain things, though, for example border color transitions. when the currency input field border changes color (either going into/out of night mode, or from/into an error state), it looks really nice.
