### ISSUE TITLE
Add AMIS Token

### ISSUE THREAD

**Issue by amisolution** [Uniswap/uniswap-frontend#391]
**Please provide the following information for your token.**

Token Address: 0x949bEd886c739f1A3273629b3320db0C5024c719
Token Name (from contract): AMIS
Token Decimals (from contract): 9
Token Symbol (from contract): AMIS
Uniswap Exchange Address of Token: 0x164c93580839f40609ce0250dd4c98a25da175de

Link to the official homepage of the token: http://erc20-amis.amisolution.net/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
