### ISSUE TITLE
Add CEL Token

### ISSUE THREAD

**Issue by maikelmclauflin** [Uniswap/uniswap-frontend#394]
**Please provide the following information for your token.**

Token Address: 0xaaaebe6fe48e54f431b0c390cfaf0b017d09d42d
Token Name (from contract): Celsius
Token Decimals (from contract): 4
Token Symbol (from contract): CEL
Uniswap Exchange Address of Token: 0x91debb54de02872a259c17699d9b794bc949fed2

Link to the official homepage of the token: https://celsius.network/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
