### ISSUE TITLE
Add IDRT Token

### ISSUE THREAD

**Issue by fengkiej** [Uniswap/uniswap-frontend#396]
Token Address: 0x998FFE1E43fAcffb941dc337dD0468d52bA5b48A
Token Name (from contract): Rupiah Token
Token Decimals (from contract): 2
Token Symbol (from contract): IDRT
Uniswap Exchange Address of Token: 0x632e120ebeb7869fe0e1ad5dbc5ab3b90a82a827

Link to the official homepage of the token: https://rupiahtoken.com/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
