### ISSUE TITLE
Add iDAI (Fulcrum/bZx DAI iToken)

### ISSUE THREAD

**Issue by tomcbean** [Uniswap/uniswap-frontend#416]
**Please provide the following information for your token.**

Token Address: 0x14094949152eddbfcd073717200da82fed8dc960
Token Name (from contract): bZx DAI iToken
Token Decimals (from contract): 18
Token Symbol (from contract): iDAI
Uniswap Exchange Address of Token: 0x81eed7f1ecbd7fa9978fcc7584296fb0c215dc5c

The icon SVG is attached:
[iDAI.zip](https://github.com/Uniswap/uniswap-frontend/files/3510654/iDAI.zip)

Link to the official homepage of the token: https://fulcrum.trade

**Comment by KyleJKistner** [comment]
Hey guys, if you added cDAI, it's only fair to add iDAI as well. 

Some context on iDAI if you're not familiar: https://medium.com/bzxnetwork/a-tour-of-the-varieties-of-dai-9ff155f7666c

**Comment by haydenadams** [comment]
There is about $5 in the liquidity pool right now supporting trades up to about $0.05 :P 

You can add liquidity here:
https://uniswap.exchange/add-liquidity?token=0x14094949152eddbfcd073717200da82fed8dc960

**Comment by tomcbean** [comment]
@haydenadams We can add liquidity. How much is needed for us to get iDAI added? Thanks.

**Comment by KyleJKistner** [comment]
Hayden, there's 50 ETH worth of liquidity now.
