### ISSUE TITLE
Add Stablecoinswap (STL)

### ISSUE THREAD

**Issue by gonchs** [Uniswap/uniswap-frontend#417]
**Please provide the following information for your token.**

Token Address: 0xc1ad68c43508dd5addb8d0ac0927dbe752d149d6
Token Name (from contract): Stablecoinswap
Token Decimals (from contract): 18
Token Symbol (from contract): STL
Uniswap Exchange Address of Token: 0xbca710302dcf84098ddae080133a8ff42e5c2379

Link to the official homepage of the token: https://stablecoinswap.io

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
