### ISSUE TITLE
Add Wrapped MarbleCards (WMC)

### ISSUE THREAD

**Issue by brianmcmichael** [Uniswap/uniswap-frontend#419]
**Please provide the following information for your token.**

Token Address: 0x8AedB297FED4b6884b808ee61fAf0837713670d0
Token Name (from contract): Wrapped MarbleCards
Token Decimals (from contract): 18
Token Symbol (from contract): WMC
Uniswap Exchange Address of Token: 0xA0db39d28dACeC1974f2a1F6Bac7d33F37C102eC

Link to the official homepage of the token: https://wrappedmarble.cards/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
