### ISSUE TITLE
PHTTOKENX PHTTX

### ISSUE THREAD

**Issue by PHTTOKENX** [Uniswap/uniswap-frontend#421]
**Please provide the following information for your token.**

Token Address: 0x8a64c0bd7146710aa5c2773365bb620faf11bed4
Token Name (from contract): PHTTOKENX
Token Decimals (from contract): 18
Token Symbol (from contract): PHTTX
Uniswap Exchange Address of Token: 0xc68f468fbc8F7446C109091C78741AdEd243232c

Link to the official homepage of the token: http://phttokenx.com/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
