### ISSUE TITLE
Add BlockState STO Token (BKN)

### ISSUE THREAD

**Issue by kaythxbye** [Uniswap/uniswap-frontend#425]
**Please provide the following information for your token.**

Token Address: 0xbee6edf5fa7e862ed2ea9b9f42cb0849184aae85
Token Name (from contract): Blockstate STO Token
Token Decimals (from contract): 0
Token Symbol (from contract): BKN
Uniswap Exchange Address of Token: 0x2eBba2D935b1e1Dc996D8f5B463C0A7628fE5880

Link to the official homepage of the token: https://blockstate.com

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
