### ISSUE TITLE
Add Tellor Tributes

### ISSUE THREAD

**Issue by themandalore** [Uniswap/uniswap-frontend#426]
**Please provide the following information for your token.**

Token Address: 0x0Ba45A8b5d5575935B8158a88C631E9F9C95a2e5
Token Name (from contract): Tellor Tributes
Token Decimals (from contract): 18
Token Symbol (from contract): TRIB
Uniswap Exchange Address of Token: 0xe28ffac44b0c430aa3e62a9bc211f7d825d6c1f9

Link to the official homepage of the token: www.tellor.io

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
