### ISSUE TITLE
Add Shuffle Monster Token (SHUF)

### ISSUE THREAD

**Issue by geomad** [Uniswap/uniswap-frontend#428]
Token Address: 0x3a9fff453d50d4ac52a6890647b823379ba36b9e
Token Name (from contract): Shuffle.Monster V3
Token Decimals (from contract): 18
Token Symbol (from contract): SHUF
Uniswap Exchange Address of Token: 0x536956fab86774fb55cfaacf496bc25e4d2b435c

Link to the official homepage of the token: https://shuffle.monster/

**Comment by Agusx1211** [comment]
Any new on this @NoahZinsmeister? Uniswap is the exchange most used for shuf, and it's weird to not be included on the default list

**Comment by Agusx1211** [comment]
also @geomad the exchange address of the token is wrong, it should be 0x536956fab86774fb55cfaacf496bc25e4d2b435c

**Comment by geomad** [comment]
Updated the exchange address.
