### ISSUE TITLE
Add BTU Protocol (BTU)

### ISSUE THREAD

**Issue by flerunigo** [Uniswap/uniswap-frontend#431]
**Please provide the following information for your token.**

Token Address: 0xb683d83a532e2cb7dfa5275eed3698436371cc9f
Token Name (from contract): BTU Protocol
Token Decimals (from contract): 18
Token Symbol (from contract): BTU
Uniswap Exchange Address of Token: 0xeA3A62838477082d8f2106c43796D636dc78d8A4

Link to the official homepage of the token: https://btu-protocol.com/

**Comment by ashleigh-schap** [comment]
@flerunigo Are you able to add liquidity to this market? As of now the exchange for BTU on uniswap does not have enough liquidity for us to add it to the frontend.
