### ISSUE TITLE
Add Invictus Hyperion Fund (IHF) to dropdown

### ISSUE THREAD

**Issue by zirs3d** [Uniswap/uniswap-frontend#436]
**Please provide the following information for your token.**

Token Address: 0xaf1250fa68d7decd34fd75de8742bc03b29bd58e
Token Name (from contract): Invictus Hyperion
Token Decimals (from contract): 18
Token Symbol (from contract): IHF
Uniswap Exchange Address of Token: 0xaeb8fb9d0a3f21ab88fc12435cdc4aae13799eb6

Link to the official homepage of the token: https://invictuscapital.com

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
