### ISSUE TITLE
Add 0xChan ICO (ZCI) token to dropdown

### ISSUE THREAD

**Issue by zirs3d** [Uniswap/uniswap-frontend#437]
**Please provide the following information for your token.**

Token Address: 0x236149288602c07b84387d0d75784d73f133142b
Token Name (from contract): 0xchan ICO
Token Decimals (from contract): 18
Token Symbol (from contract): ZCI
Uniswap Exchange Address of Token: 0xcfcc608f03c0cee86589e11224f24779212f0fe5

Link to the official homepage of the token: https://0xchan.net

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
