### ISSUE TITLE
Add Huobi Token to dropdown

### ISSUE THREAD

**Issue by zirs3d** [Uniswap/uniswap-frontend#438]
**Please provide the following information for your token.**

Token Address: 0x6f259637dcd74c767781e37bc6133cd6a68aa161
Token Name (from contract): HuobiToken
Token Decimals (from contract): 18
Token Symbol (from contract): HT
Uniswap Exchange Address of Token: 0x60058Dd4cbaB1870D2B8741FAb24725A2F110054
_(Not the same namespace as HypeToken:HT)_

Link to the official homepage of the token: https://www.hbg.com (formerly - `https://huobipro.com`)

Currently ranked 15 listed on CoinMarketCap:
Huobi Token (HT) is an exchange based token and native currency of the Huobi crypto exchange. The HT can be used to purchase monthly VIP status plans for transaction fee discounts, vote on exchange decisions, gain early access to special Huobi events, receive crypto rewards from seasonal buybacks and trade with other cryptocurrencies listed on the Huobi exchange.

**Comment by zirs3d** [comment]
Huobi API Github repo:
https://github.com/huobiapi 

API Documentation
https://huobiapi.github.io/docs/spot/v1/en/#introduction

**Comment by haydenadams** [comment]
@zirs3d 

Do you work with Huobi Token? We'd be happy to add it if a bit more liquidity is added to Uniswap. Right now there is only ~$400. 

The following link can be used to add liquidity 
http://uniswap.exchange/add-liquidity?token=0x6f259637dcd74c767781e37bc6133cd6a68aa161

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time because the liquidity for this market is too low, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
