### ISSUE TITLE
Add liquidity - Use exchange rate for second deposit and cause first deposit to 0.1 instead of 1

### ISSUE THREAD

**Issue by jacklinTT** [Uniswap/uniswap-frontend#439]
**Bug Description**
Use exchange rate for second deposit and cause first deposit to 0.1 instead of 1.

**Steps to Reproduce**
1. Go to Pool.
2. Choose ETH as first deposit type.
3. Choose DAI as second deposit type.
4. Enter number which is exactly the same with current exchange rate for second deposit.
5. Number of first deposit will become 0.1 instead of 1.

**Expected Behavior**
Amount of 1 for first deposit instead of 0.1.

** Screenshot **
![add_liquidity_wrong_deposit](https://user-images.githubusercontent.com/50574948/64395628-801f1e80-d08d-11e9-9cf9-86b41630f4d6.png)

**Comment by NoahZinsmeister** [comment]
this was fixed by https://github.com/Uniswap/uniswap-frontend/commit/61d6556a0d2521fcbdbaabfcc66c758747f92c45!

**Comment by jacklinTT** [comment]
Hi Noah:
Thanks for your fix and response.
