### ISSUE TITLE
Add liquidity - Warning messages of "Insufficient Balance" and "Please unlock token to continue" will display in turns within a short time in "Add liquidity" of Pool

### ISSUE THREAD

**Issue by jacklinTT** [Uniswap/uniswap-frontend#450]
**Bug Description**
Warning messages of "Insufficient Balance" and "Please unlock token to continue" will display in turns within a short time in "Add liquidity" of Pool for every 23+ seconds.

**Steps to Reproduce**
1. Go to Pool and choose "Add liquidity."
2. Choose unlocked token as first deposit type and enter affordable amount of value.
3. Choose any token which has not been unlocked before as second deposit type.
4. "Insufficient Balance" and "Please unlock token to continue" will take turns to display within a short time for every 23+ seconds. But it's hard to see "Please unlock token to continue" with the naked eye during transition.

**Expected Behavior**
Separate lines of warning message or concatenated message.

**Screenshot**
![Uniswap_pool_add_liquidity_insufficient_balance_unlock_1](https://user-images.githubusercontent.com/50574948/65417050-c87b6200-de2b-11e9-8441-4542b330b520.png)
![Uniswap_pool_add_liquidity_insufficient_balance_unlock_2](https://user-images.githubusercontent.com/50574948/65417067-d29d6080-de2b-11e9-967c-da180ebb8212.png)

**Comment by ianlapham** [comment]
Thanks for the insight - I'll take a look and get the error more consistent
