### ISSUE TITLE
Seeds Token Addition

### ISSUE THREAD

**Issue by playseeds** [Uniswap/uniswap-frontend#454]
**Please provide the following information for your token.**

Token Address: 0x61404d2d3f2100b124d6827d3f2ddf6233cd71c0
Token Name (from contract): Seeds
Token Decimals (from contract): 10
Token Symbol (from contract): SEEDS
Uniswap Exchange Address of Token: 0x1DceA7A07579C8F7638E2863e07C682581d3740C

Link to the official homepage of the token: seedsgives.com

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
