### ISSUE TITLE
Please add BitcoinSoV to DropDown

### ISSUE THREAD

**Issue by HashTablesNet** [Uniswap/uniswap-frontend#455]
**Please provide the following information for your token.**

Token Address: 0x26946adA5eCb57f3A1F91605050Ce45c482C9Eb1
Token Name (from contract): BitcoinSoV
Token Decimals (from contract): 8
Token Symbol (from contract): BSOV
Uniswap Exchange Address of Token: 0x87CcbfD2d46d167d9e7488255680F48c2Ad0C5Bb

Link to the official homepage of the token: https://bsov.io

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
