### ISSUE TITLE
Token Request: BAND

### ISSUE THREAD

**Issue by touhonoob** [Uniswap/uniswap-frontend#456]
Token Address: 0xBA11D00c5f74255f56a5E366F4F77f5A186d7f55
Token Name (from contract): BandToken
Token Decimals (from contract): 18
Token Symbol (from contract): BAND
Uniswap Exchange Address of Token: 0x88616Cf228FFb3fB8ba336592A79A53De53D05eF

Link to the official homepage of the token: https://bandprotocol.com

**Comment by ashleigh-schap** [comment]
Hello, we have added some new questions to the token request listing form. Can you please review and answer? Thank you!

**Comment by sorawit** [comment]
Hi @ashleigh-schap. I just submitted the listing form. Looking forward to hearing back from you. Thanks!

**Comment by sorawit** [comment]
@NoahZinsmeister Can you help provide the guideline for what we need do to get listed on Uniswap frontend? We already submitted the google form. Thanks!
