### ISSUE TITLE
Add EBASE

### ISSUE THREAD

**Issue by prgmtx** [Uniswap/uniswap-frontend#457]
Token Address: 0x86fadb80d8d2cff3c3680819e4da99c10232ba0f
Token Name (from contract): EURBASE Stablecoin
Token Decimals (from contract): 18
Token Symbol (from contract): EBASE
Uniswap Exchange Address of Token: 0x376b59b5d35a7cc8c052684842697f102d79d04a

Link to the official homepage of the token: https://eurbase.com/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe

**Comment by prgmtx** [comment]
@ashleigh-schap what is the reason that EBASE cannot be added to the Uniswal frontend?
