### ISSUE TITLE
Add XBASE

### ISSUE THREAD

**Issue by prgmtx** [Uniswap/uniswap-frontend#458]
Token Address: 0x4d13d624a87baa278733c068a174412afa9ca6c8
Token Name (from contract): Eterbase Coin
Token Decimals (from contract): 18
Token Symbol (from contract): XBASE
Uniswap Exchange Address of Token: 0x6f5a3dea184d3c3110b804827fe7fb859d82a79e

Link to the official homepage of the token: https://www.eterbase.com/

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe

**Comment by prgmtx** [comment]
What is the reason that XBASE cannot be added to the Uniswal frontend?
