### ISSUE TITLE
XNC Token

### ISSUE THREAD

**Issue by ersanyakit** [Uniswap/uniswap-frontend#459]
**Please provide the following information for your token.**

Token Address: 0x8317b216D7c3F9a5B8401E4b6814D13A7BE390ec
Token Name (from contract): EXNCE
Token Decimals (from contract): 8
Token Symbol (from contract): XNC
Uniswap Exchange Address of Token: 0xe04bC8D7C6E49aE6fb193F0A995046eF63D6526B

Link to the official homepage of the token:https://www.exnce.com

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
