### ISSUE TITLE
ETHPLODE Token Request

### ISSUE THREAD

**Issue by ersanyakit** [Uniswap/uniswap-frontend#461]
**Please provide the following information for your token.**

Token Address: 0xe0c6ce3e73029f201e5c0bedb97f67572a93711c
Token Name (from contract): ETHPLODE
Token Decimals (from contract): 6
Token Symbol (from contract): ETHPLO
Uniswap Exchange Address of Token: 0x59af19879e9dcd298b9f1ad2b1ee5f5f7ed2d332

Link to the official homepage of the token:https://www.ethplode.org

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time, but here is a resource for creating a custom link: https://docs.uniswap.io/frontend-integration/linking and here is a resource for creating an iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
