### ISSUE TITLE
Add Mars Equity (MRQ) token to dropdown

### ISSUE THREAD

**Issue by densmirnov** [Uniswap/uniswap-frontend#471]
**Please provide the following information for your token.**

Token Address: 0xc651e99f40d908b6a606d54f221b414b5228ff60
Token Name (from contract): MarsEquity
Token Decimals (from contract): 18
Token Symbol (from contract): MRQ
Uniswap Exchange Address of Token: 0x22f32524A1eDf73d192737e869a8881fc95A8c15

Link to the official homepage of the token: https://unidao.fund

Are you able to add liquidity to the liquidity pool for this token? **Yes**
If so, how much liquidity are you able to add (USD)? **As much as required**

**Comment by ashleigh-schap** [comment]
We are not able to add frontend support for this token at this time if you would like to create a custom link, here are instructions: https://docs.uniswap.io/frontend-integration/linking
