### ISSUE TITLE
New Token: APX

### ISSUE THREAD

**Issue by cvhessert** [Uniswap/uniswap-frontend#483]
Token Address: 0x1239562abe89ff62016ae23d4e6eef12b915295c
Token Name (from contract): APEX
Token Decimals (from contract): 18
Token Symbol (from contract): APX
Uniswap Exchange Address of Token: 0x81daD92a06b96e24800d74cf112966Dc941f994f

**Comment by ashleigh-schap** [comment]
Unfortunately we're not able to add support for this token right now but please see https://docs.uniswap.io/frontend-integration/linking for help with custom linking! Thank you.
