### ISSUE TITLE
Token Request: Add Quantstamp Token (QSP)

### ISSUE THREAD

**Issue by palladionrm** [Uniswap/uniswap-frontend#487]
**Please provide the following information for your token.**

Token Address: 0x99ea4db9ee77acd40b119bd1dc4e33e1c070b80d
Token Name (from contract): Quantstamp Token
Token Decimals (from contract): 18
Token Symbol (from contract): QSP
Uniswap Exchange Address of Token: 0x82db9fc4956fa40efe1e35d881004612b5cb2cc2

Link to the official homepage of the token: [https://quantstamp.com/ ](https://quantstamp.com/)
Link to Coinmarketcap page of token: [https://coinmarketcap.com/currencies/quantstamp/](https://coinmarketcap.com/currencies/quantstamp/)

Some tokens (e.g. Binance token) do not work with uniswap. In order to assess if your token works correctly, please complete transactions of each of the below type and submit the etherscan transaction links for our review: 
Test swap transaction: [https://etherscan.io/tx/0xc9f9ce1aa3f688376042b56236d2fd8a868f53a1db29e74a33297294d1fe1377](https://etherscan.io/tx/0xc9f9ce1aa3f688376042b56236d2fd8a868f53a1db29e74a33297294d1fe1377)
Test addLiquidity transaction: [https://etherscan.io/tx/0x4c2efaf539d7cb8345768281cc25d1da53661ad660d31dd236b677a9a4788d65](https://etherscan.io/tx/0x4c2efaf539d7cb8345768281cc25d1da53661ad660d31dd236b677a9a4788d65)
Test removeToken transaction: [https://etherscan.io/tx/0x1e60dab2131f2e428455573d7039f95c9ef5655cb88304092d6fa7b3769f7db6](https://etherscan.io/tx/0x1e60dab2131f2e428455573d7039f95c9ef5655cb88304092d6fa7b3769f7db6)

Are you able to add liquidity to the liquidity pool for this token? (Y/N) Y
If so, how much liquidity are you able to add (USD)? 1000

**Comment by ashleigh-schap** [comment]
@palladionrm Hi Richard! We're happy to add support for QSP but the liquidity on the exchange is a bit low. Are you guys able to add liquidity to the exchange? It would be great if you could encourage your token holders to participate as well!
