### ISSUE TITLE
Can't remove liquidity from particular pool

### ISSUE THREAD

**Issue by macro655** [Uniswap/uniswap-frontend#488]
**Bug Description**
Can't remove liquidity from a particular token's (0x0cbe2df57ca9191b64a7af3baa3f946fa7df2f25) liquidity pool. No response after clicking remove liquidity. No issue performing the same action on other tokens. 

**Steps to Reproduce**
1. Go to remove liquidity page 
2. Go to 0x0cbe2df57ca9191b64a7af3baa3f946fa7df2f25 token
3. Select maximum balance 
4. Click remove liquidity
5. Nothing happens

**Expected Behavior**
1. Metamask pop-up for transaction approval

**Additional Context**
Using a Ledger Nano S, via Metamask. Have tried using Firefox, Chrome and Brave.

**Comment by ianlapham** [comment]
Hey, it seems like this is an issue with this specific exchange (as swapping doesn't work either). Working through it now.

**Comment by ianlapham** [comment]
Quick update here, looks like this isn't an issue with just liuqidity withdrawl, but any interactions with that token in general (As swapping is broken too). It may have to do with the way they are upgrading those contracts - I'll try a few things and see if there's a way to get the txn to go through.

**Comment by yvikhlya** [comment]
Any news on this issue? Just found that I can't withdraw old sUSD too.

**Comment by yvikhlya** [comment]
Any updates on this issue? My funds got stuck in the pool too.

**Comment by macro655** [comment]
Thanks for following up on this Yury, my tokens are still there as well.

**Comment by yvikhlya** [comment]
This is what web console prints out:
```
MetaMask - RPC Error: gas required exceeds allowance (9943416) or always failing transaction
```
What does this mean? Is this actually uniswap or metamask or token contract issue?

**Comment by garthtravers** [comment]
Hi @macro655 shoot an email over to support@synthetix.io and we'll sort you out.
