### ISSUE TITLE
Token Request: COD

### ISSUE THREAD

**Issue by erbileren** [Uniswap/uniswap-frontend#489]
**Please provide the following information for your token.**

Token Address: 0xf2ccd161f06d88479b50d4bedbad9992dbdaffdd
Token Name (from contract): Colendi Token
Token Decimals (from contract): 18
Token Symbol (from contract): COD
Uniswap Exchange Address of Token: 0x3Db809EC27B89E35FcD506DB7f95cD2e6864eecA

Link to the official homepage of the token: https://token.colendi.com/
Link to Coinmarketcap page of token: -

Some tokens (e.g. Binance token) do not work with uniswap. In order to assess if your token works correctly, please complete transactions of each of the below type and submit the etherscan transaction links for our review: 
Test swap transaction: 0x55f3c2f8f4c02bfda4540287c493dcdfb869d29a0a650fe50e221d808889f6cb 
Test addLiquidity transaction: 0x0670cc51ff2f1f8bf688ed68235faa8ed313d5641629167285e9eda3f8f377d2
Test removeToken transaction: -

Are you able to add liquidity to the liquidity pool for this token? (Y/N) Y
If so, how much liquidity are you able to add (USD)? 86.56 (already added)

**Comment by ashleigh-schap** [comment]
@erbileren There is not enough demand to add support for COD to uniswap frontend at this time. However, we would recommend adding an iframe integration to your website to allow users to trade there. Instructions here: https://docs.uniswap.io/frontend-integration/iframe
