### ISSUE TITLE
Add VectorspaceAI (VXV) Token

### ISSUE THREAD

**Issue by w07wong** [Uniswap/uniswap-frontend#492]
Token Address: 0x7d29a64504629172a429e64183d6673b9dacbfce
Token Name (from contract): VectorspaceAI
Token Decimals (from contract): 18
Token Symbol (from contract): VXV
Uniswap Exchange Address of Token: 0x7b9b5084aff35d3e9d87fb1e384853b806120bed

Link to the official homepage of token: https://vectorspace.ai/
Link to CoinMarketCap page of token: https://coinmarketcap.com/currencies/vectorspace-ai/

**Comment by ashleigh-schap** [comment]
@w07wong Unfortunately we are not able to add front end support for this token at this time. However, to make trading easier for your users, you are able to create a custom iframe integration for your website: https://docs.uniswap.io/frontend-integration/iframe
