### ISSUE TITLE
Token Request: Add LMY Token

### ISSUE THREAD

**Issue by LunchMoneyToken** [Uniswap/uniswap-frontend#494]
**Please provide the following information for your token.**

Token Address: 0x66fd97a78d8854fec445cd1c80a07896b0b4851f
Token Name (from contract): Lunch Money
Token Decimals (from contract): 18
Token Symbol (from contract): LMY
Uniswap Exchange Address of Token: 0xeCE1d9e03ad03e89A9b0944776551E5B6b23578E

Link to the official homepage of token: https://www.lunchmoney.io/
Link to CoinMarketCap page of token: https://coinmarketcap.com/currencies/lunchmoney/
Link to Coingecko page of token: https://www.coingecko.com/en/coins/lunch-money

Some tokens (e.g. BNB) do not work with Uniswap v1. In order to assess if your token works correctly, please complete small-value transactions of each of the types below, and submit the Etherscan transaction links for our review.
Test `addLiquidity` transaction: 
https://etherscan.io/tx/0x084477d291d64d4352ba34d27fe0544386fef5c7698609e75abd48fafb6db45c

Test `swap` transaction: 
https://etherscan.io/tx/0xd87ca23714a946571dbe9f1752412a53c55f4823347ff481dd5446481c8aeb1b

Test `removeLiquidity` transaction: 
https://etherscan.io/tx/0x0d224af0d7136d08206bfa632b115abf6235af7396b4885b4f740fdd6c9d3a9f

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): Y
If so, how much liquidity are you willing to add?: 1 ETH or more

**Comment by ashleigh-schap** [comment]
@LunchMoneyToken We are not able to add support for this token to our frontend at this time, however you are able to use custom linking to share the exchange with your users: https://docs.uniswap.io/frontend-integration/linking and you can also add an iframe to your site: https://docs.uniswap.io/frontend-integration/iframe
