### ISSUE TITLE
Token Request: FKX

### ISSUE THREAD

**Issue by aaronmboyd** [Uniswap/uniswap-frontend#497]
**Please provide the following information for your token.**

Token Address: 0x009e864923b49263c7f10d19b7f8ab7a9a5aad33
Token Name (from contract): Knoxstertoken
Token Decimals (from contract): 18
Token Symbol (from contract): FKX
Uniswap Exchange Address of Token: 0x91aa9d58d0672E3E4B0dAd9AbFE41c8849baB571

Link to the official homepage of token: https://fortknoxster.com
Link to CoinMarketCap page of token: https://coinmarketcap.com/currencies/fortknoxster/

Some tokens (e.g. BNB) do not work with Uniswap v1. In order to assess if your token works correctly, please complete small-value transactions of each of the types below, and submit the Etherscan transaction links for our review.
Test `addLiquidity` transaction: 0x15654b26abea18203967b6f8154d492118cdc5ca1efdcd696080824f294a1548
Test `swap` transaction: 0x3a0c65fa373ae3b139380674f0df026a424398e7da2fada0aa8d4fe007e6ecae
Test `removeLiquidity` transaction: 0x9b5f09aa1ac43ce22c720258da4606d16b0c320ca819512cfacbd01b0d5d088c

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): Y
If so, how much liquidity are you willing to add?: 50,000 FKX ~= .5 ETH. Potentially more I can buy from Kucoin to get it going. Have circulated on the FKX Telegram that a Uniswap exchange contract is available for FKX, will try and get more liquidity added and get arbitrateurs monitoring the exchange.

**Comment by ashleigh-schap** [comment]
@aaronmboyd Unfortunately we do not yet have enough demand for liquidity for this token to add it to our frontend. If FKX users add more liquidity to the exchange, please resubmit a request and we will review it again. Thank you!
