### ISSUE TITLE
Token logos not loading

### ISSUE THREAD

**Issue by PaulRBerg** [Uniswap/uniswap-frontend#500]
**Bug Description**
From Trust Wallet's [assets](https://github.com/trustwallet/assets/) repo:

> On November 8th 2019 we made big changes to the repository, please read summary and recommendations

Among others, they checksummed the URL path for every token. Uniswap still uses the lowercase version.

**Expected Behavior**
Logos should load.

**Additional Context**

<img width="658" alt="Uniswap Screen Capture" src="https://user-images.githubusercontent.com/8782666/68514576-cc056400-0286-11ea-9666-22ebfaa5ea2c.png">

**Comment by vikmeup** [comment]
https://raw.githubusercontent.com/trustwallet/assets/master/blockchains/ethereum/assets/0x006BeA43Baa3f7A6f765F14f10A1a1b08334EF45/logo.png

We need to pass checksum address to get an image

or use old branch: https://raw.githubusercontent.com/trustwallet/assets/old/blockchains/ethereum/assets/0x006bea43baa3f7a6f765f14f10a1a1b08334ef45/logo.png

had to make last breaking change for architecture of our assets data
