### ISSUE TITLE
Add Santiment Network Token (SAN) to Uniswap

### ISSUE THREAD

**Issue by tzanko-matev** [Uniswap/uniswap-frontend#502]
**Please provide the following information for your token.**

Token Address: 0x7c5a0ce9267ed19b22f8cae653f198e3e8daf098
Token Name (from contract): Santiment network token
Token Decimals (from contract): 18
Token Symbol (from contract): SAN
Uniswap Exchange Address of Token: 0x8a8d7ad4b89d91983cd069c58c4aa9f2f4166298

Link to the official homepage of token: https://santiment.net
Link to CoinMarketCap page of token: https://coinmarketcap.com/currencies/santiment/

Some tokens (e.g. BNB) do not work with Uniswap v1. In order to assess if your token works correctly, please complete small-value transactions of each of the types below, and submit the Etherscan transaction links for our review. 
Test `addLiquidity` transaction: https://etherscan.io/tx/0xdb21e4fb3a6c8f82c32f5e15aee12d2046789791247b6da6e222c2ae0a82e505
Test `swap` transaction: https://etherscan.io/tx/0x76c998d05ccecac4a8d82c416d2afe1b81bc7d4abb9a5dc6993b72e602eb1b6f
Test `removeLiquidity` transaction: https://etherscan.io/tx/0xc8adb851054fd34f861ff435ec198ffb495b1929e0e02bf82eb5043dd5877106

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): 
If so, how much liquidity are you willing to add?: 10000 SAN

**Comment by ashleigh-schap** [comment]
@tzanko-matev Are you able to add the 10000 SAN to the liquidity pool this week?

**Comment by tzanko-matev** [comment]
It's done
