### ISSUE TITLE
Request of add my custom token to uniswap

### ISSUE THREAD

**Issue by sakbayeme2015** [Uniswap/uniswap-frontend#507]
**Please provide the following information for your token.**

Token Address:   0x897aE96D0b8759Ba2C56372BD6316d8Dd62e7365
Token Name (from contract):  Dai
Token Decimals (from contract): 18
Token Symbol (from contract): Dai
Uniswap Exchange Address of Token:  0xae345A936B4573e70fDCD852D4505496e95F3A6B
Uniswap factory address : 0x0b9bE3364Aac5c5b9c28bc89a4B6cF007e0248FB

**Comment by ashleigh-schap** [comment]
Unfortunately we can't add support for this token right now, but you can use a custom token link: https://docs.uniswap.io/frontend-integration/linking

Thank you!

**Comment by sakbayeme2015** [comment]
please , i want your help

is it possible to use the uniswap exchange contract address to exchange my
custom tokens
