### ISSUE TITLE
iframe always includes scrollbars

### ISSUE THREAD

**Issue by MicahZoltu** [Uniswap/uniswap-frontend#512]
**Bug Description**
When including Uniswap as an iframe, it always has scrollbars, even when you give plenty of space for the contents.

**Steps to Reproduce**
1. `<iframe style="width: 615px; height: 768px; border: none; overflow: hidden;" scrolling="no" src="https://uniswap.exchange/swap"></iframe>`
2. Notice the scrollbars.
...

**Expected Behavior**
No scrollbars.

**Additional Context**
The problem can be seen when loading Uniswap on any browser.  There are scrollbars even if you have _way_ more than enough space.  Part of the problem is that there are forced scrollbars due to styling from https://github.com/Uniswap/uniswap-frontend/blob/production/src/theme/index.js#L125

The other part of the problem is that the page currently includes more vertical content than can fit on the page.  Fixing this will require adjustments to the way you are space filling, but you can also see this problem outside of an iframe by loading the page in a very large browser window and noting that despite the excessive amount of available space, you can still vertically scroll.

**Comment by ianlapham** [comment]
Fixed here https://github.com/Uniswap/uniswap-frontend/pull/513
