### ISSUE TITLE
Wallet Connect qr code modal doesn't work in Safari

### ISSUE THREAD

**Issue by PaulRBerg** [Uniswap/uniswap-frontend#523]
**Bug Description**
The option card in the Wallet Connect qr code modal does not render correctly in Safari.

**Steps to Reproduce**
1. Install dependencies and yarn start
2. Go to localhost:3000 on Safari
3. Tap "Connect to a wallet"
4. Tap "Wallet Connect"

**Expected Behavior**
The option card should render correctly.

**Additional Context**
I was on the `beta` branch, commit `bcf480e7586ac1b3f474019c0596fcfdc1579632`.

This thread on StackOverflow is possibly related: [CSS Grid does not work in Firefox and Safari](https://stackoverflow.com/questions/49954587/css-grid-does-not-work-in-firefox-and-safari).

<img width="512" alt="Capture d’écran 2019-11-30 à 23 25 36" src="https://user-images.githubusercontent.com/8782666/69906217-bb996280-13c8-11ea-93d9-81705b78832d.png">

**Comment by ianlapham** [comment]
close here #528
