### ISSUE TITLE
Can't used in imToken wallet

### ISSUE THREAD

**Issue by chezhe** [Uniswap/uniswap-frontend#536]
**Bug Description**
The DApp doesn't render normally, as js exception

**Steps to Reproduce**
![Screen Shot 2019-12-05 at 14 30 35](https://user-images.githubusercontent.com/2902414/70289557-17704b00-1810-11ea-8156-e68e1cc01936.png)
![Screen Shot 2019-12-05 at 15 06 09](https://user-images.githubusercontent.com/2902414/70289561-1b03d200-1810-11ea-9a00-b4e8ec5da0e5.png)

Got errors above, after recent updates. It works before yesterday.

**Expected Behavior**

**Comment by NoahZinsmeister** [comment]
fixed!
