### ISSUE TITLE
Orchid (OXT) POOL - Orchid’s Decentralized VPN Network 

### ISSUE THREAD

**Issue by bneiluj** [Uniswap/uniswap-frontend#550]
Please provide the following information for your token.

1. Token Address: `0x4575f41308ec1483f3d399aa9a2826d74da13deb `
2. Token Name (from contract): `Orchid `
3. Token Decimals (from contract): `18` 
4. Token Symbol (from contract): `OXT`
5. Uniswap Exchange Address of Token:`0xe9a5bbe41dc63d555e06746b047d624e3343ea52`
6. Link to the official homepage of token: https://www.orchid.com/
7. Link to CoinMarketCap page of token: `not listed.`

Some tokens (e.g. BNB) do not work with Uniswap v1. In order to assess if your token works correctly, please complete small-value transactions of each of the types below, and submit the Etherscan transaction links for our review. 
 1. Test addLiquidity transaction:  https://etherscan.io/tx/0x1da00d00b1a215cefdf059ea0bd21c5b6ffa6e1b0233642c7c91615beed9f07e (+303 OXT +0.67 ETH) 
2. Test swap transaction:  https://etherscan.io/tx/0x0efddc58e04b248486b47998b8f1546a86366917a0d731931aa0bf51da60e9e0 (15 oxt for 0.034 ETH) 
3. Test removeLiquidity transaction:  https://etherscan.io/tx/0x6bcf1393a7f835b115054a39e07576eb2399fdc8153a5d77e9cb6a3448039133 (-44.64 OXT ; -0.1 ETH)

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): Y If so, how much liquidity are you willing to add?: 

`~$20,000.00. And already ~$10,000.00 been added.`

<img width="1381" alt="Screenshot 2019-12-10 at 23 00 23" src="https://user-images.githubusercontent.com/3680497/70573671-c01d0280-1ba2-11ea-8116-c745eb6ee8f8.png">

**Comment by NoahZinsmeister** [comment]
closed by #553
