### ISSUE TITLE
NaN crash from normalizeBigNumberish()

### ISSUE THREAD

**Issue by pi0neerpat** [Uniswap/uniswap-frontend#556]
**Bug Description**
Eth <> custom token causes page to crash with `normalizeBigNumberish()`

**Steps to Reproduce**
1. [https://uniswap.exchange/swap](https://uniswap.exchange/swap)
2. In either input/output enter custom token `0xd24d520eb55ea010998303110fa188673122416a`
3. Page crashes with error message:
```
Error: "Passed bigNumberish 'NaN' of type 'object' is notvalid."
    normalizeBigNumberish
```
...

**Additional Context**
I believe I have narrowed it down to a nothing being passed to [`tradeExactEthForTokensWithData()`](https://github.com/Uniswap/uniswap-sdk/blob/1fcc0a59cd960e4ed0465c7714557688c01b31fe/src/orchestration/index.ts#L14) for `ethAmount`. However I cannot find this here in the frontend repo, only in the SDK.

@jschiarizzi

**Comment by NoahZinsmeister** [comment]
closed by #557

**Comment by NoahZinsmeister** [comment]
for now the fix is only https://beta.uniswap.exchange

**Comment by pi0neerpat** [comment]
Thanks yall rock! :)
