### ISSUE TITLE
Add FAME

### ISSUE THREAD

**Issue by daihovey** [Uniswap/uniswap-frontend#566]
Token Address: 
`0x06f65b8cfcb13a9fe37d836fe9708da38ecb29b2`
Token Name (from contract): 
`SAINT FAME: Genesis Shirt`
Token Decimals (from contract): 
`18`
Token Symbol (from contract): 
`FAME`
Uniswap Exchange Address of Token: 
`0x5e7907ac70b9a781365c72f2acee96710bda042e`
Link to the official homepage of token:
https://saintfame.com

**Comment by NoahZinsmeister** [comment]
added
