### ISSUE TITLE
Cannot connect metamask using ropsten network ?

### ISSUE THREAD

**Issue by abcfy2** [Uniswap/uniswap-frontend#573]
**Bug Description**

**Steps to Reproduce**
1. edit `.env.local` set `REACT_APP_NETWORK_ID="3"` and `REACT_APP_NETWORK_URL="https://ropsten.infura.io/v3/<my_key>"`
2. `yarn start`
3. set metamask network to ropsten
4, connect to metamask

**Expected Behavior**
Ropsten network should work.

**Additional Context**
connect to metamask failed.

![image](https://user-images.githubusercontent.com/5327677/71323301-81753980-250c-11ea-91d5-d21e663e3d7a.png)

**Comment by NoahZinsmeister** [comment]
ah, my apologies @abcfy2 , the README is a bit out of date. you'll actually have to edit [this line](https://github.com/Uniswap/uniswap-frontend/blob/beta/src/connectors/index.js#L17) to include `3` for ropsten. we are working on making the multi-network stuff easier to do, but do let me know if this fixes your immediate issue.

**Comment by abcfy2** [comment]
Thank you. It's working.

After change `supportedChainIds: [1]` to `supportedChainIds: [1, 3]`, it's working.
