### ISSUE TITLE
WalletConnect QRCode either too small or unreadable when using dark mode

### ISSUE THREAD

**Issue by miguelmota** [Uniswap/uniswap-frontend#579]
The walletconnect qrcode cannot be read when using a javascript qrcode reader because the qrcode is either too small or unreadable when using the dark theme. Suggestion would be to use a white square as the background for the qrcode or make it large since reading the qrcode on the wallet connect example site works just fine.

**Comment by yannis182del** [comment]
has this been fixed ??

**Comment by miguelmota** [comment]
Works with the new redesign
