### ISSUE TITLE
Fix 0 decimal tokens issue

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#597]
0x20d4cec36528e1c4563c1bfbe3de06aba70b22b4

Swap crashes, add/remove fail (rate at 0)

Only the first addLiquidity event succeeds (rate not set yet)

**Comment by ianlapham** [comment]
0 decimal tokens work when eth per token rate is < 1 (MOD for example). But for this token the eth rate is 1.6 so the big number division breaks. Working on a fix for that specifc case.

**Comment by ChristophSiegenthaler** [comment]
I think this issue is closed now, isn't it? #601

**Comment by NoahZinsmeister** [comment]
yup!
