### ISSUE TITLE
Uniswap iframe doesn't load if using Brave and have shields up 

### ISSUE THREAD

**Issue by anader123** [Uniswap/uniswap-frontend#605]
When viewing a page that is using the Uniswap iframe, Brave browser users won't be able to view the exchange interface. The modal is just blank and the error "DOMException: Failed to read the 'localStorage' property from 'Window': Access is denied for this document." appears in the console. 

Turning off the Brave shields for the website, allows the frame to load with no errors. The issue might have to do with the cookie settings that are default for Brave.  Brave is probably picking up cookies from uniswap while on the other app website and blocking the whole iframe from loading.

**Comment by NoahZinsmeister** [comment]
closing in favor of #718
