### ISSUE TITLE
Can't remove liquidity for a specific token. 

### ISSUE THREAD

**Issue by maidabarrientos** [Uniswap/uniswap-frontend#633]
**Bug Description**
Can't remove liquidity for token CTB - > https://etherscan.io/tx/0xfe12c8a97d250e3ce8e0857167590216a69ed3f255d334d4f6d89ad4c98d39a3

**Steps to Reproduce**
1. Go to uniswap.exchange
2. Click on Pool->And click on Remove Liquidity
3. Input the remaining pool token for CTB - > 0x43c1c012aa89c60019b4e941ccac98f22d2f3c01
4. 0.0083
5. And then Remove liquidity, the Metamask window will appear. Then what I did was up the gas to $12 and clicked Confirm
...

**Expected Behavior**
1. Should have removed liquidity so I can add again?
I'd like to add our token again because the calculation or rather the conversion was incorrect. It should have been pegged at $0.10 per CTB or 0.00036804ETH per CTB

**Additional Context**
Add any other context about the problem here (screenshots, whether the bug only occurs only in certain mobile/desktop/browser environments, etc.)

**Comment by x5engine** [comment]
same issue 

I cant get back my liquidity from my custom token

**Comment by x5engine** [comment]
might be related?

https://github.com/Uniswap/uniswap-frontend/issues/635
