### ISSUE TITLE
Page goes blank when searching for a custom token

### ISSUE THREAD

**Issue by x5engine** [Uniswap/uniswap-frontend#635]
**Bug Description**

`Uncaught Error: Passed bigNumberish 'Infinity' of type 'object' is not valid.`

**Steps to Reproduce**
1. Go to https://uniswap.exchange
2. Click on Add liquidity 
3. Paste token number `0x6B099E9AC8Dc9f3C0Fbb56087A90768E8c801364`
4. page goes blank (check screenshot)
5. i lost my 0.08 eth :'(
...

![image](https://user-images.githubusercontent.com/12363020/74544679-d26f4000-4f47-11ea-913f-2f4912c73311.png)

**Comment by PaulRBerg** [comment]
I can also confirm that this bug occurs when pasting the address of a token that has no exchange.

<img width="695" alt="Capture d’écran 2020-03-24 à 15 43 14" src="https://user-images.githubusercontent.com/8782666/77432156-5be71d00-6de6-11ea-8d6b-3fe2a1c1b77b.png">

**Comment by x5engine** [comment]
yeah,

> The ting goes skrrah (Ah)
Pop, pop, ka-ka-ka (Ka-ka)
Skidi-ki-pop-pop (Pah)
And a pu-pu-brr-boom (Boom)
Ski-ya (Ah)

@PaulRBerg it's not when it has no exchange but when sometimes the token is not propagated properly between their nodes or whatever... if you load it after a few days or the same browser you created the token it works properly... but this error should be handled the right way
