### ISSUE TITLE
ARX Gas fee is too high to use

### ISSUE THREAD

**Issue by LeGaryGary** [Uniswap/uniswap-frontend#667]
**Bug Description**
When swapping / pooling ARX the following error is seen in the console:
![Screenshot from 2020-03-30 15-13-00](https://user-images.githubusercontent.com/19892506/77922471-ffc64200-7298-11ea-8b58-8ddb287758fc.png)

**Steps to Reproduce**
1. Go to https://uniswap.exchange/swap?outputCurrency=0X9B7D9AAEF003C0CBA76A6556E0EBBC117144E9F9
2. Attempt to swap any quantity of ETH to ARX
3. The error above is generated in the console

**Expected Behavior**
A reasonable gas price is offered so that I can exchange my tokens, add/remove liquidity to the pool

**Additional Context**
The token is https://arxtoken.com/ with ERC20 contract address 0X9B7D9AAEF003C0CBA76A6556E0EBBC117144E9F9

**Comment by LeGaryGary** [comment]
Hi, could you explain why you closed this issue?

**Comment by NoahZinsmeister** [comment]
we've significantly overhauled the codebase to interact with Uniswap V2, if you're having issues with ARX on the current site, feel free to open another issue.

if this problem persists only on v1 (deployed for now at https://v1.uniswap.exchange), then i'm afraid we don't really have the bandwidth to investigate. if you're having trouble removing liquidity, please get in touch via our [Discord](https://discord.gg/Y7TF6QA)
