### ISSUE TITLE
Add BTC++

### ISSUE THREAD

**Issue by MickdeGraaf** [Uniswap/uniswap-frontend#670]
**Please provide the following information for your token.**

Token Address: 0x0327112423f3a68efdf1fcf402f6c5cb9f7c33fd
Token Name (from contract): PieDAO BTC++
Token Decimals (from contract): 18
Token Symbol (from contract): BTC++
Uniswap Exchange Address of Token: 0x0b5e26829B72654620cD431E685FD71ad956E58E

Link to the official homepage of token: https://piedao.org
Link to CoinMarketCap or CoinGecko page of token: n/a

Are you willing to add liquidity to the liquidity pool for this token? (Y/N): Y
If so, how much liquidity are you willing to add?: More than 10BTC++ already comitted

**Comment by dimarconicola** [comment]
@MickdeGraaf do you have specs for the token icon so I can add it?

**Comment by MickdeGraaf** [comment]
> @MickdeGraaf do you have specs for the token icon so I can add it?

I've opened a PR to the trustwallet repo which Uniswap uses afaik.

**Comment by Alexintosh** [comment]
+1

**Comment by nigeon** [comment]
+1

**Comment by dimarconicola** [comment]
+1

**Comment by dmvt** [comment]
+1

**Comment by NoahZinsmeister** [comment]
+1s are not helpful, this is what emotes are for.

closed by [b54c20d](https://github.com/Uniswap/uniswap-frontend/commit/b54c20d56b3054906a8f4063bcb3be6457b518d8)
