### ISSUE TITLE
Walletconnect not scannable in dark mode

### ISSUE THREAD

**Issue by ligi** [Uniswap/uniswap-frontend#692]
I can't scan the QR codes in the dark mode:

![Selection_435](https://user-images.githubusercontent.com/111600/80273637-44949b80-86d4-11ea-9fb6-ba58f7b67e9a.png)

In light mode the scanning works fine:

![Selection_436](https://user-images.githubusercontent.com/111600/80273645-65f58780-86d4-11ea-8fba-9ee44e5e907c.png)

I think the QR code area should stay white/black instead of using the theme colors.

**Comment by ligi** [comment]
cc @pedrouid

**Comment by pedrouid** [comment]
This qrcode is generated by custom UI.

@NoahZinsmeister could you take a look?

**Comment by NoahZinsmeister** [comment]
this should be fixed
