### ISSUE TITLE
ISLA Token Image

### ISSUE THREAD

**Issue by Calum-Insula** [Uniswap/uniswap-frontend#770]
Hi there, Insula token ISLA, is already on Uniswap. However our logo does not currently appear when the token is searched for, an emoji appears to be there as a placeholder. 

https://uniswap.info/token/0x697ef32b4a3f5a4c39de1cb7563f24ca7bfc5947

We would like our logo to appear next to the token name as it does for other tokens on the site. I have attached a copy of it here. 

<img width="82" alt="ins" src="https://user-images.githubusercontent.com/65359532/81961433-46ce8380-960a-11ea-8c29-a79308247663.png">

**Comment by NoahZinsmeister** [comment]
we pull icons from https://github.com/trustwallet/assets

**Comment by Calum-Insula** [comment]
I see. Our logo is now in https://github.com/trustwallet/assets in the correct folder. Could you give me a time frame for when we can expect to see our logo appear on the site?
