### ISSUE TITLE
Improve pool list performance 

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-frontend#802]
Loading the pool list can result in freezes or degraded scrolling behavior.

> On the exchange web app set to v2, on up-to-date Firefox on up-to-date macOS, there is a consistent bug that doesn't allow me to scroll through the pools. The cursor doesn't blink either so it seems the "select a pool" window just freezes up once it comes up. This resolves itself after about 45 seconds of waiting (which is a lot)

**Comment by moodysalem** [comment]
should be fixed
