### ISSUE TITLE
Improvement: Web page loading speed

### ISSUE THREAD

**Issue by jin10086** [Uniswap/uniswap-frontend#811]
I just used jsdeliver's cdn service,can save me a lot of time

you can go to https://www.jsdelivr.com/ for more information

my website: https://igaojin.me/uniswap-frontend/

github: https://github.com/jin10086/uniswap-frontend/tree/gh-pages

## How i did it:
- Create a new reop (https://github.com/jin10086/uniswap-frontend-cdn
- add `PUBLIC_URL="https://cdn.jsdelivr.net/gh/jin10086/uniswap-frontend-cdn@master/build/"` in `.env.local`file 
- yarn build && cp -rf build ../uniswap-frontend-cdn 
- in uniswap-frontend-cdn  ,`git add * && git commit -m "go" && git push`
- deploy

before:

![image](https://user-images.githubusercontent.com/15347911/82388431-2d936000-9a6c-11ea-9dde-c511355f3bd0.png)

after:

![image](https://user-images.githubusercontent.com/15347911/82388490-54519680-9a6c-11ea-8f5d-e32c961d6f72.png)

**Comment by jin10086** [comment]
My location: Shanghai

**Comment by moodysalem** [comment]
We are unlikely to serve from a different CDN than Netlify's own CDN, but IPFS may help with this. I created this issue #814 for that

**Comment by moodysalem** [comment]
Try the ipfs gateways listed here
https://github.com/Uniswap/uniswap-frontend/releases/tag/v2.0.0
