### ISSUE TITLE
Consider automatically closing pop-ups after submitting a transaction

### ISSUE THREAD

**Issue by haydenadams** [Uniswap/uniswap-frontend#821]
could replace with one of these that says transaction submitted that you can click on for more details

<img width="917" alt="Screen Shot 2020-05-20 at 5 36 05 PM" src="https://user-images.githubusercontent.com/9343483/82499841-65c48e00-9ac0-11ea-87c5-a0645d345ad4.png">

**Comment by moodysalem** [comment]
I like this idea, obsoletes #799

**Comment by callil** [comment]
I prefer keeping the submitted in the modal. I think the two feel disconnected and don’t really like having 2 notifications happen for 1 transaction. 

Are you concerned people feel like they have to leave the transaction submitted view open?

**Comment by haydenadams** [comment]
Some people were saying it felt like an unnecessary extra step / click

**Comment by callil** [comment]
Connecting #824 into this discussion

I think there is a path here where we: 
1. Add the staged slippage confirm modal (where >25% you have to type to proceed) #800 
2. Add expert mode toggle in advanced to bypass confirm modals (type to confirm mode) #824
3. Add submitted notification for when you have this toggled (this issue)
