### ISSUE TITLE
Add expert mode toggle to bypass confirms

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-frontend#824]
For power users who are making >10 trades a day the confirm modal can get tiring. Consider a local storage flag with a switch in advanced to bypass the confirm dialogs.

**Comment by bpsib** [comment]
Now some deluded morons decided to remove this option last month without any explanation whatsoever. This has made me so angry. WHY THE HELL HAS THIS OPTION BEEN REMOVED???
