### ISSUE TITLE
Support of fee-on-transfer tokens

### ISSUE THREAD

**Issue by realrouse** [Uniswap/uniswap-frontend#835]
**Is your feature request related to a problem? Please describe.**
The Uniswap v2 front-end doesn't support deflationary tokens. (tokens that burn a % of each transaction, like the one I'm contributing to, "BSOV" (https://bsov.io).
BSOV Token Request: https://github.com/Uniswap/uniswap-frontend/issues/836
Deflation is very important for the deflationist community, and many of us wish that BSOV keeps on burning, while trading on-chain.

**Describe the solution you'd like**
Possibly like @NoahZinsmeister described to me in the Discord: A feature in the Uniswap v2 front-end that lets the user "set their slippage to whatever % deflation they expect from their token".

**Describe alternatives you've considered**
When there is a token request of a deflationary token on Github, then there could be a custom parameter that could be prefixed for easier implementation of deflationary tokens in the Uniswap v2 front-end, so the user would not need to set their slippage for **every** trade, to match the % deflation.

**Additional context**
While I don't know how to develop these things, then there are several things I can help you with, like paying you some BSOV or doing tasks revolving Media & Communication (like design and videos).

**Comment by ciconsulting** [comment]
I believe this issue also affects tokens that have a transfer and/or storage fee.  In v1 there didn't seem to be an issue but with v2 it requires fee exemption of the router and pool address which is a less than ideal solution (particularly having to exempt the pool from storage fees) but it does some to work.   

Transfer and storage fees are not very common features but there are a few examples.  This will probably become more common as tokens backed by real assets gain in popularity.

**Comment by NoahZinsmeister** [comment]
For posterity, a summary of the status of fee-on-transfer (FoT) tokens on Uniswap V2 follows. Note that this also applies to tokens which deflate on transfer, but does _not_ necessarily apply to tokens which deflate in other ways.

**Swapping**
{W,}ETH -> FoT swaps will succeed, _provided that the slippage set by the user is >= the expected deflation/fee_.

FoT -> {W,}ETH swaps will fail, _but may be supported in a future router release_.

**Adding/Removing Liquidity**
Adding/removing liquidity will succeed, _provided that the slippage set by the user is >= the expected deflation/fee_.

**Comment by NoahZinsmeister** [comment]
For those wishing to manually remove their FoT<>WETH liquidity before a fix is released on our end, steps to do so follow:

# Manually Removing Liquidity for WETH<>Deflationary Token Pairs

## Step 1: Approve the Uniswap router to transfer your pool tokens

- Look up the address of the pair you have liquidity in by visiting https://etherscan.io/address/0x5c69bee701ef814a2b6a3edd4b1652cb9cc5aa6f#readContract (the Uniswap factory) and pasting the token addresses into `getPair`. For ETH, use 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 (the WETH address).

- Visit https://etherscan.io/address/<PAIR_ADDRESS>#writeContract (the pair), click Connect to Web3, and execute an `approve` with the following parameters:
  - spender: 0xf164fC0Ec4E93095b804a4795bBe1e041497b92a (the Uniswap router)
  - value: 115792089237316195423570985008687907853269984665640564039457584007913129639935 (the maximum value)

## Step 2: Burn your pool tokens

- Visit https://etherscan.io/address/0xf164fC0Ec4E93095b804a4795bBe1e041497b92a#writeContract (the router), click Connect to Web3, and execute a `removeLiquidity` with the following parameters:
  - tokenA: <YOUR_TOKEN_ADDRESS> (your token address)
  - tokenB: 0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2 (WETH)
  - liquidity: <YOUR_LIQUIDITY_BALANCE> (to get this, visit https://etherscan.io/address/<PAIR_ADDRESS>#readContract and paste <YOUR_ADDRESS> into `balanceOf`)
  - amountAMin: 0 (this is safe, removing liquidity always gives you a pro rata share)
  - amountBMin: 0 (this is safe, removing liquidity always gives you a pro rata share)
  - to: <YOUR_ADDRESS>
  - deadline: <UNIX_TIMESTAMP> (to get this, visit https://www.unixtimestamp.com/ and add 1200 (20 minutes) to the current value)

## Step 3 (Optional): Convert your WETH to ETH

- Visit https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2#writeContract (WETH), click Connect to Web3, and execute a `withdraw` with the following parameters:
  - liquidity: <YOUR_WETH_BALANCE> (to get this, visit https://etherscan.io/address/0xC02aaA39b223FE8D0A0e5C4F27eAD9083C756Cc2#readContract and paste <YOUR_ADDRESS> into `balanceOf`)

**Comment by MirasolFerrer** [comment]
So we can never ever remove liquidity with burning tokens? What would be an ideal solution or alternative for this? I might face loss for this one.

**Comment by realrouse** [comment]
> So we can never ever remove liquidity with burning tokens? What would be an ideal solution or alternative for this? I might face loss for this one.

If you read what @NoahZinsmeister wrote in the post above, you can Remove Liquidity by following his guide above.

**Comment by MirasolFerrer** [comment]
> > So we can never ever remove liquidity with burning tokens? What would be an ideal solution or alternative for this? I might face loss for this one.
> 
> If you read what @NoahZinsmeister wrote in the post above, you can Remove Liquidity by following his guide above.

Even if its a deflationary token?

**Comment by ciconsulting** [comment]
Can confirm it works even if it’s a deflationary token or a token that has a transfer fee.

**Comment by MirasolFerrer** [comment]
> Can confirm it works even if it’s a deflationary token or a token that has a transfer fee.

Lastly, its deflationary, but paired with ETH, would still work?

**Comment by NoahZinsmeister** [comment]
yes @MirasolFerrer, please stop cluttering the conversation.

**Comment by NoahZinsmeister** [comment]
removing Fot <> WETH liquidity into ETH should now work on the frontend

FoT -> ETH/token swaps should now work on the frontend

two notes on swaps:
- all swaps involving FoT tokens must specify an exact input, not an exact output
- all swaps involving FoT tokens must have slippage set to at least the fee percentage

**Comment by realrouse** [comment]
> removing Fot <> WETH liquidity into ETH should now work on the frontend
> 
> FoT -> ETH/token swaps should now work on the frontend
> 
> two notes on swaps:
> 
> * all swaps involving FoT tokens must specify an exact input, not an exact output
> * all swaps involving FoT tokens must have slippage set to at least the fee percentage

Thank you for the swift development, @NoahZinsmeister ! 
I was wondering:
1. If there could be made a custom URL to set the slippage to the ease of our users?
2. If it is possible to develop a workaround so that you are able to specify exact output?
3. Is it possible that the slippage could be set automatically when you for example list a FoT token like BSOV (https://bsov.io) ?
4. Should I create another issue about this, or is this comment sufficient?

If there is anything you'd need help with, Noah, let me know! 😁

**Comment by NoahZinsmeister** [comment]
> If there could be made a custom URL to set the slippage to the ease of our users?
tracking in #876

> If it is possible to develop a workaround so that you are able to specify exact output?
we are not going to be supporting this on the default frontend, you are welcome to come up with a custom solution.

> Is it possible that the slippage could be set automatically when you for example list a FoT token like BSOV (https://bsov.io) ?
it's unlikely

**Comment by evinke** [comment]
I just posted this on reddit:
https://www.reddit.com/r/UniSwap/comments/hs6uqf/problem_with_removing_tokens_and_eth_from_ampl/

Can this be related to this issue? When will this be fixed in the frontend? I might have migrated from V1 to V2, but I am not sure...

**Comment by Fukunaga42** [comment]
Hey guys we have the same on our DTH/ETH pair https://uniswap.info/pair/0xC0Cb62f0b5C9574Cc88907dC0712F27b4a6a60c1.
Users in front-end are not able to remove their liquidity, The workaround describes heres works, but how can we do to make it works directly from your front-end?

**Comment by NoahZinsmeister** [comment]
removing liquidity for FoT tokens works on the frontend, you just have to specify a slippage higher than the fee

**Comment by a7om** [comment]
Just put an issue in that is similar to this that relates to UMA. Can't withdraw any pool tokens, signing the transaction always fails.

**Comment by shivasai780** [comment]
Can anyone explain me what is the difference between swaptokens and swaptokenssupporting feeto

**Comment by italoHonoratoSA** [comment]
> Can anyone explain me what is the difference between swaptokens and swaptokenssupporting feeto

Here the details:
https://docs.uniswap.org/protocol/V2/reference/smart-contracts/router-02

**Comment by push-it-forward** [comment]
Why can the LP tokens not be removed for 

https://www.dextools.io/app/ether/pair-explorer/0x95930b9d954af3e5707c314cbedf6973fcdf8bf7

Our team has attempted front end and through Etherscan as mentioned above....we can't even migrate it to V3.

@NoahZinsmeister help?

**Comment by push-it-forward** [comment]
Can anybody help here?

**Comment by cache-gold** [comment]
I believe we have discovered a work around for transfer fee tokens that works with our [CACHE Gold (CGT) token](https://github.com/cache-token/docs).  Our token has both a fee on transfer and a [storage fee](https://github.com/cache-token/docs/blob/master/FEES.md).  The solution is to exempt:

The Uniswap v3 Factory contract - [0x1F98431c8aD98523631AE4a59f267346ea31F984 ](https://etherscan.io/address/0x1f98431c8ad98523631ae4a59f267346ea31f984)

The Uniswap v3 Positions contract - [0xC36442b4a4522E871399CD717aBDD847Ab11FE88](https://etherscan.io/address/0xc36442b4a4522e871399cd717abdd847ab11fe88) 

Our own Uniswap v3 Pool contract(s) - [0x98eb3887B6c2CD50341aF13E26BA5111Ec585c57](https://etherscan.io/address/0x98eb3887b6c2cd50341af13e26ba5111ec585c57)

In our experience if you are developing any type of token that has fees of any kind in addition to standard Ethereum gas fees, it is advisable to make sure you build in a function to exempt specific addresses from fees, especially if you want your token to be compatible with existing and future DeFi infrastructure. 

Right now we are testing [our new v3 pool](https://info.uniswap.org/#/pools/0x98eb3887b6c2cd50341af13e26ba5111ec585c57) and everything seems to be working as expected.  

The solution described above also worked for v2.

Hope this helps.

**Comment by push-it-forward** [comment]
These are the available functions to call for our team

https://etherscan.io/address/0xabd8f6cd6b1f9ee6ca88528a4fccff84093a23e8#writeContract

<img width="687" alt="Screen Shot 2022-04-21 at 7 20 36 AM" src="https://user-images.githubusercontent.com/96081767/164478739-4cc6140e-1001-4b54-b175-2246ad356867.png">

I'm afraid we're completely stuck here on why we can't migrate to V3 or even withdraw the tokens / W (ETH) .. we can't afford to take a loss here and are willing to award ETH to anybody who can figure this out.

**Comment by italoHonoratoSA** [comment]
> These are the available functions to call for our team
> 
> https://etherscan.io/address/0xabd8f6cd6b1f9ee6ca88528a4fccff84093a23e8#writeContract
> 
> <img alt="Screen Shot 2022-04-21 at 7 20 36 AM" width="687" src="https://user-images.githubusercontent.com/96081767/164478739-4cc6140e-1001-4b54-b175-2246ad356867.png">
> 
> I'm afraid we're completely stuck here on why we can't migrate to V3 or even withdraw the tokens / W (ETH) .. we can't afford to take a loss here and are willing to award ETH to anybody who can figure this out.

I have already solved similar cases with many BNB stuck. I went through that too once.

My question? why did you renounce the contract?

**Comment by push-it-forward** [comment]
@italoHonoratoSA 

Renounced for increased investor security.

Sounds like you've done this before, and team has approved to give half the W (ETH) in the LP to the one who can help us.

Hoping we can somehow do it (open to anything pulling via Uniswap, etherscan, or migrating to v3)

**Comment by sswink** [comment]
How does the uniswap/pancakeswap front end know to use the SupportingFeeOnTransferTokens functions when interacting with my contract?
