### ISSUE TITLE
Some JS functions compatibility issues on low android phone

### ISSUE THREAD

**Issue by zhen6939** [Uniswap/uniswap-frontend#838]
**Bug Description**
Some JS functions compatibility issues on low android phone

**Steps to Reproduce**
1. Using imToken v2.5.6.843, phone vivo X21，Android 9
2. Go to Browser tab,  click Uniswap 

**Expected Behavior**
Open Uniswap as usual

**Additional Context**
![image](https://user-images.githubusercontent.com/6891736/82999071-168bd980-a03b-11ea-87eb-e1ab63ba6118.png)

**Comment by moodysalem** [comment]
presume it's `flatMap`:
https://caniuse.com/#feat=array-flat

**Comment by moodysalem** [comment]
give it another try and please close the issue if it works now

**Comment by NoahZinsmeister** [comment]
closing as solved, please reopen or file another issue if the problem persists
