### ISSUE TITLE
“You are the first liquidity provider...” message flashes when navigating directly to Add Liquidity page

### ISSUE THREAD

**Issue by danrobinson** [Uniswap/uniswap-frontend#842]
**Bug Description**
When navigating directly to an Add Liquidity page via the URL, the “You are the first liquidity provider” message flashes for a moment, even if there is already liquidity in the pair.

**Steps to Reproduce**
1. Go to https://uniswap.exchange/add/0x6b175474e89094c44da98b954eedeac495271d0f-0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2. (It lasts longer when the internet connection is slow.)
...

**Expected Behavior**
No message flashed.

**Comment by moodysalem** [comment]
I caused this because we don't accurately detect the loading state in the new `usePair`
