### ISSUE TITLE
We are ready to add XAL in this week update to the exchange frontend!

### ISSUE THREAD

**Issue by omurgokyar** [Uniswap/uniswap-frontend#846]
Hello
I received this email from Uniswap Listing Department at Mon, 27 Apr 2020 - 12:26:10 PM +0300

> Hello!

> Heads-up from us about your Uniswap listing request - we are ready to
add XAL in this week update to the exchange frontend, however we've
found out that you haven't yet met token liquidity requirements for
ETH-token pair.
According to our rules, you should transfer a deposit of at least 3 ETH
to setup the liquidity pool required for trading on Uniswap. If you
would like to get into this week listing update, please return this
email asap and we'll assist you further.

> Best regards,
> Joshua Breslav,
> Uniswap listing department

Then i replied at Wed, 29 Apr 2020 - 09:59:56 AM +0300

> Hello!
> I transfered a deposit 3 ETH to setup the liquidity pool.
> This is Transaction Link : https://etherscan.io/tx/0x436f24294de047a9fb37d0ccb703430db5c63e459f3036278fcfe5fee1f9a015

After 35 days there was no improvement in the situation.
Please can you give me a positive or negative answer. I emailed you but nobody answered.

Best Regard
Ömür Gökyar
Founder & CTO
Altın Lira | XAL

**Comment by NoahZinsmeister** [comment]
this email is an impersonation @omurgokyar, Uniswap has never had, does not, and never will have a listing department. please be careful on the internet.
