### ISSUE TITLE
Can't swap KICK tokens

### ISSUE THREAD

**Issue by ThomasdenH** [Uniswap/uniswap-frontend#849]
**Bug Description**
I have received KICK tokens on my account that I would like to swap. The slippage is quite high at 23.88%, bu I don't really care about that. I have set the slippage tolerance at 49%. The interface is stuck at 'Waiting For Confirmation' and no promt appears.

**Steps to Reproduce**
1. Choose to swap 888888 KICK tokens for SXAU tokens.
2. Set the slippage tolerance to a high number, e.g. 49%.
3. Click on 'Swap Anyway' and confirm the slippage is acceptable in the extra prompt.
...

**Expected Behavior**
Metamask appears with a transaction dialog, but instead nothing happens.

**Additional Context**
The following messages appear in my console:
- `MetaMask - RPC Error: gas required exceeds allowance (9990259) or always failing transaction 
Object { code: -32000, message: "gas required exceeds allowance (9990259) or always failing transaction" }
inpage.js:1:79970
`
- `Swap or gas estimate failed 
Object { code: -32000, message: "gas required exceeds allowance (9990259) or always failing transaction" }
useSwapCallback.ts:196:18
`
- `uncaught exception: Object
`

Edit: The route taken is KICK -> ETH -> USDC -> SXAU, maybe that's too long?
Edit 2: The same issue happens when converting to ETH.

**Comment by NoahZinsmeister** [comment]
I believe KICK tokens are frozen, you should take this up with the team

**Comment by ThomasdenH** [comment]
Ah, that makes sense. I think they're spam tokens, that's how they maintain their price I guess. Thanks!
