### ISSUE TITLE
Mass notifications triggered

### ISSUE THREAD

**Issue by callil** [Uniswap/uniswap-frontend#854]
Hard refreshed the frontend and saw this:
<img width="430" alt="Screen Shot 2020-06-03 at 1 16 52 PM" src="https://user-images.githubusercontent.com/1355319/83667786-f4470e00-a59c-11ea-9fab-00f4f3eb9288.png">

Trying to reproduce or find other info. Nothing in console.

**Comment by moodysalem** [comment]
Fixed by https://github.com/Uniswap/uniswap-frontend/commit/6de3a6ec28f6d726fe9a4f56839826a54e79a49f
