### ISSUE TITLE
Cant remove liquidity on tokens subject to burning. 

### ISSUE THREAD

**Issue by MirasolFerrer** [Uniswap/uniswap-frontend#863]
Since this is already a problem that tokens subject to burning and paired with eth can be removed as liquidity, what can be an alternative solution for this especially to those who might suffer from losses?

**Comment by moodysalem** [comment]
Issue and workaround (including steps to remove your liquidity) here
https://github.com/Uniswap/uniswap-frontend/issues/835#issuecomment-635469820
